# Generated by Django 3.2 on 2022-04-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id_departemen', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'ref_departemen',
                'managed': False,
            },
        ),
    ]
