from django.db import models

EXPORT_HEADERS = [ 'ID_SEGMENT','NAMA_SEGMENT', 'ALAMAT','ID_GARDU_INDUK','ID_TRAFO_GI','ID_PENYULANG','ID_ZONE','ID_SECTION','LATITUDE','LONGITUDE','STATUS','EVENT_UPLOAD']

EXPORT_HEADERS_DATA = ['ID_SEGMENT','NAMA_SEGMENT', 'ALAMAT','NAMA_GARDU_INDUK','NAMA_TRAFO_GI','NAMA_PENYULANG','ID_ZONE','ID_SECTION','NAMA_SECTION','LATITUDE','LONGITUDE','STATUS']