


EXPORT_HEADERS = ['ID_KANTOR','NAMA_KANTOR','ALAMAT', 'ID_JENIS_KANTOR','ID_UNIT_INDUK', 'LATITUDE','LONGITUDE','STATUS','EVENT_UPLOAD']

EXPORT_HEADERS_DATA = ['ID_KANTOR','NAMA_KANTOR','ALAMAT', 'NAMA_JENIS_KANTOR','ID_UNIT_INDUK', 'NAMA_UNIT_INDUK','UP3','LATITUDE','LONGITUDE','STATUS']