"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from django.conf import settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/ 

from .env import * 

SECRET_KEY = get_env_value('SECRET_KEY')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # cors
    'corsheaders',
    # rest framework
    'rest_framework',
    # swager
    'drf_spectacular',
    #filters
    'django_filters',
    #xml
    'rest_framework_xml',

    # test endpont
    'apps.test_endpoint',
    'apscheduler',


    # apps/endpoint

    #tests 
    # 'apps.tests.send_email',
    'apps.tests.multi_insert.trans_rekap_padam',
    'apps.tests.multi_insert.trans_rekap_padam_peralatan',
    'apps.tests.multi_insert.trans_rekap_padam_section',

    'apps.authapi',
    'apps.users',
    'apps.roles',
    'apps.menu',
    # 'apps.master.jaringan',
    'apps.master.jaringan.ref_lokasi',
    'apps.master.jaringan.ref_jenis_lokasi',
    'apps.master.jaringan.ref_jenis_pembangkit',
    'apps.master.jaringan.ref_lokasi_gd',
    'apps.master.jaringan.ref_pemilik_jaringan',
    'apps.master.jaringan.tree_jaringan',
    #master wilayah
    'apps.master.wilayah.ref_province',
    'apps.master.wilayah.ref_regency',
    'apps.master.wilayah.ref_district',
    'apps.master.management_upload',
    'apps.master.management_upload.unit_pembangkit',
    'apps.master.management_upload.gardu_induk',
    'apps.master.management_upload.pembangkit',
    'apps.master.management_upload.trafo_gi',
    'apps.master.management_upload.penyulang',
    'apps.master.management_upload.zona',
    'apps.master.management_upload.section',
    'apps.master.management_upload.segment',
    'apps.master.management_upload.gardu_distribusi',
    'apps.master.management_upload.gardu_hubung',
    'apps.master.management_upload.trafo_gd',
    'apps.master.aset.ref_aset',
    'apps.master.aset.ref_aset_doc',
    'apps.master.aset.ref_aset_ex_atr',
    'apps.master.aset.ref_aset_ext_atr',
    'apps.master.aset.ref_aset_jenis',
    'apps.master.aset.ref_aset_manufaktur',
    'apps.master.aset.ref_aset_lantai',
    'apps.master.aset.ref_aset_ruangan',
    'apps.master.aset.ref_aset_rak',
    'apps.master.aset.ref_aset_kondisi',
    'apps.master.aset.ref_aset_level',
    'apps.master.aset.ref_aset_status',
    'apps.master.aset.ref_aset_jenis_mutasi',


    #Master Wroking Permit
    'apps.master.working_permit.pertanyaan_qrc',
    'apps.master.working_permit.risk_point_qrc',
    'apps.master.working_permit.larangan_tanggung_jawab_mitra',
    'apps.master.working_permit.approval_management_wp',
    'apps.master.working_permit.wm_bagian',
    'apps.master.working_permit.ref_kel_pekerjaan',
    'apps.master.working_permit.ref_kel_keselamatan',

    

    #master WR
    'apps.master.wr.ref_wr_status',

    # Master Pegawai
    'apps.master.pegawai.departemen',
    'apps.master.pegawai.jabatan',
    'apps.master.pegawai.perusahaan',
    'apps.master.pegawai.ref_pegawai',
    'apps.master.pegawai.ref_regu_petugas',

    #application_setting
    'apps.application_setting',

    #trans
    'apps.trans.trans_pm_jenis_doc',
    'apps.trans.opsisdis.trans_wo_log_status',
    'apps.trans.opsisdis.trans_wo',
    'apps.trans.opsisdis.trans_pm',
    'apps.trans.opsisdis.trans_pm_detail',
    'apps.trans.opsisdis.trans_aset_mutasi',

    #fasop_scada
    'apps.master.fasop.path1',
    'apps.master.fasop.path3',
    'apps.master.fasop.pm',
    'apps.master.fasop.master',
    'apps.master.fasop.rtu',
    'apps.master.fasop.point_type',
    'apps.master.fasop.point_type_state',
    'apps.master.fasop.telegram_bot',
    'apps.master.fasop.telegram_group',
    'apps.master.fasop.telegram_log',
    'apps.master.fasop.c_point',

    # master opsisdis
    'apps.master.opsisdis.jenis_penyebab_gangguan',
    'apps.master.opsisdis.penyebab_gangguan',
    'apps.master.opsisdis.frekuensi',
    'apps.master.opsisdis.amr_customer',
    'apps.master.opsisdis.ref_jenis_pekerjaan',
    
    'apps.master.opsisdis.rekap_padam.ref_ep_fiohl',
    'apps.master.opsisdis.rekap_padam.ref_ep_indikasi',
    'apps.master.opsisdis.rekap_padam.ref_ep_petugas',
    'apps.master.opsisdis.rekap_padam.ref_ep_rupiah',
    'apps.master.opsisdis.rekap_padam.ref_ep_cuaca',
    'apps.master.opsisdis.rekap_padam.ref_ep_penyebab_ggn',
    'apps.master.opsisdis.rekap_padam.ref_ep_fdir',

    # opsisdis master pm
    'apps.master.opsisdis.pm.ref_hi',
    'apps.master.opsisdis.pm.ref_pm',
    'apps.master.opsisdis.pm.ref_pm_detail',
    'apps.master.opsisdis.pm.ref_pm_detail_logic',

    #opsisdis master WO
    'apps.master.opsisdis.wo.ref_wo_jenis',
    'apps.master.opsisdis.wo.ref_wo_status',
    
    'apps.opsisdis.telemetring.pembangkit',
    'apps.opsisdis.telemetring.trafo_gi_non_ktt',
    'apps.opsisdis.telemetring.penyulang',
    'apps.opsisdis.telemetring.zona',
    'apps.opsisdis.telemetring.area',
    'apps.opsisdis.telemetring.wilayah',
    'apps.opsisdis.telemetring.amr_energi',
    'apps.opsisdis.telemetring.amr_load_profile',
    'apps.opsisdis.frekuensi.scd_trans_frek_5m',
    'apps.opsisdis.frekuensi.scd_trans_frek_his',
    'apps.opsisdis.frekuensi.scd_frek_rtl',
    'apps.opsisdis.frekuensi.scd_frek_th',
    'apps.opsisdis.frekuensi.backup_harian',

    #opsis laporan beban
    'apps.opsisdis.laporan_beban.trans_tm_trafo_gi_jam',
    'apps.opsisdis.laporan_beban.trans_tm_trafo_gi_hari',
    'apps.opsisdis.laporan_beban.trans_tm_trafo_gi_bulan',
    'apps.opsisdis.laporan_beban.trans_tm_trafo_gi_tahun',
    'apps.opsisdis.laporan_beban.trans_tm_penyulang_jam',
    'apps.opsisdis.laporan_beban.trans_tm_penyulang_hari',
    'apps.opsisdis.laporan_beban.trans_tm_penyulang_bulan',
    'apps.opsisdis.laporan_beban.trans_tm_penyulang_tahun',
    'apps.opsisdis.laporan_beban.trans_tm_up3',
    'apps.opsisdis.laporan_beban.trans_tm_up3_hari',
    'apps.opsisdis.laporan_beban.trans_tm_up3_bulan',
    'apps.opsisdis.laporan_beban.trans_tm_up3_tahun',
    'apps.opsisdis.laporan_beban.trans_tm_up2b_jam',
    'apps.opsisdis.laporan_beban.trans_tm_up2b_hari', 
    'apps.opsisdis.laporan_beban.trans_tm_up2b_bulan',
    'apps.opsisdis.laporan_beban.trans_tm_up2b_tahun',
    'apps.opsisdis.laporan_beban.trans_tm_uid_jam',
    'apps.opsisdis.laporan_beban.trans_tm_uid_hari',  
    'apps.opsisdis.laporan_beban.trans_tm_uid_bulan',
    'apps.opsisdis.laporan_beban.trans_tm_uid_tahun',
    'apps.opsisdis.laporan_beban.trans_tm_subsistem_jam',
    'apps.opsisdis.laporan_beban.trans_tm_subsistem_hari',  
    'apps.opsisdis.laporan_beban.trans_tm_subsistem_bulan',
    'apps.opsisdis.laporan_beban.trans_tm_subsistem_tahun',

    #JADWAL PEMELIHARAAN
    'apps.opsisdis.jadwal_pemeliharaan.trans_jadwal_har',
    'apps.opsisdis.jadwal_pemeliharaan.trans_jadwal_har_dok',
    'apps.opsisdis.jadwal_pemeliharaan.trans_jadwal_har_gardu',
    #ufr
    'apps.opsisdis.urf.penyulang_urf',
    # external
    'apps.external.ext_user_token',
    'apps.external.ext_user_token_role',
    'apps.external.ext_module',

    #fasop histori
    'apps.fasop.histori.scd_his_analog',
    'apps.fasop.histori.scd_his_digital',
    'apps.fasop.histori.scd_his_rtu',
    'apps.fasop.histori.scd_his_master',
    # 'apps.fasop.histori.scd_his_message',
    'apps.fasop.histori.scd_his_analog_30m',
    'apps.fasop.histori.scd_his_trip',
    'apps.fasop.histori.scd_his_rc',
    #FASOP KINERJA
    'apps.fasop.kinerja.scd_kin_digital_bulan',
    'apps.fasop.kinerja.scd_kin_digital_harian',
    'apps.fasop.kinerja.scd_kin_rtu_bulan',
    'apps.fasop.kinerja.scd_kin_rtu_harian',
    'apps.fasop.kinerja.scd_kin_analog_bulan',
    'apps.fasop.kinerja.scd_kin_analog_harian',
    'apps.fasop.kinerja.scd_kin_master_bulan',
    'apps.fasop.kinerja.scd_kin_master_harian',

    #FASOP REALTIM
    'apps.fasop.realtime.scd_analog_rtl',
    'apps.fasop.realtime.scd_digital_rtl',
    'apps.fasop.realtime.scd_rtu_rtl',
    'apps.fasop.realtime.scd_master_rtl',

    #apkt
    'apps.apkt.apkt_trans_jar',
    'apps.apkt.apkt_trans_jar_det',
    'apps.apkt.apkt_trans_log',

    #working permit
    # 'apps.working_permit.wp_bagian',
    'apps.working_permit.wp_hirarc',
    'apps.working_permit.wp_hirarc_detail',
    'apps.working_permit.wp_master_sop_jsa',
    'apps.working_permit.wp_qrc',
    'apps.working_permit.wp_qrc_detail', 
    'apps.working_permit.wp_qrc_tmp',  
    'apps.working_permit.wp_ttd_online',
    'apps.working_permit.wp_online',
    'apps.working_permit.wp_online_pekerja',
    'apps.working_permit.wp_aproval_ttd',
    'apps.working_permit.wp_dok',
    'apps.working_permit.wp_sop_perlengkapan',

    #OPSISDIS SLD
    'apps.opsisdis.sld.daf_sld_gi',

    #histori
    'apps.histori.users_his_password',
    #opsisdis rekap padam
    'apps.opsisdis.rekap_padam.trans_ep',
    'apps.opsisdis.rekap_padam.trans_ep_laporan',
    'apps.opsisdis.rekap_padam.trans_ep_peralatan',
    'apps.opsisdis.rekap_padam.trans_ep_section',

    #laporan scada
    'apps.fasop.realtime_scd',
    'apps.fasop.soe_alarm_proteksi',
    'apps.fasop.histori_rc',
    'apps.fasop.kinerja_rc',
    'apps.fasop.histori_peralatan_scd',
    'apps.fasop.kinerja_peralatan_scd',

    
    # dashboard
    'apps.dashboard.kinerja_scd',

    'apps.latihan.latihan1',
    # authtoken
    # 'rest_framework.authtoken'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # cors
    'corsheaders.middleware.CorsMiddleware',
    'base.custom_exception_handler.ExceptionMiddleware',
]

ROOT_URLCONF = 'core.urls'

# rest framework setting
REST_FRAMEWORK = {
    #work with sort & filtering
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTTokenUserAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer', 
        # 'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_xml.renderers.XMLRenderer'
    ), 
    #xml
    'DEFAULT_CONTENT_NEGOTIATION_CLASS': 'base.negotiation.CustomContentNegotiation',
    #djangofilterbackend filters
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'SEARCH_PARAM': 'keyword',
    'ORDERING_PARAM': 'sort_by',
    'EXCEPTION_HANDLER': 'base.custom_exception_handler.handle_exception'
}

# drf swagger setting
SPECTACULAR_SETTINGS = {
    'TITLE': 'APD',
    'DESCRIPTION': 'Swagger APD',
    'VERSION': '1.0.0',
    'SORT_OPERATION_PARAMETERS': False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest',
    'SWAGGER_UI_FAVICON_HREF': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/favicon-32x32.png',
    # 'SWAGGER_UI_FAVICON_HREF': os.path.join(settings.STATICFILES_DIRS,'favicon.png') ,
    'REDOC_DIST': 'https://cdn.jsdelivr.net/npm/redoc@latest',
    # OTHER SETTINGS
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/apd/',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id_user',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
#hidewarning
# SILENCED_SYSTEM_CHECKS = ["auth.W004"]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'id-ID'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = os.path.join(BASE_DIR, 'static/')

# BASE FOLDER
BASE_ROOT = os.path.join(BASE_DIR, 'base')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# media folder configZ
MEDIA_ROOT = os.path.join(BASE_DIR, 'templates/media')
MEDIA_ROOT_FREKWENSI = os.path.join(BASE_DIR, 'templates/media/frekwensi')
MEDIA_URL = 'templates/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# corsorigin headers
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# Custom user model
AUTH_USER_MODEL = "users.Users"
APPEND_SLASH = True

#email config
EMAIL_BACKEND = get_env_value('EMAIL_BACKEND')
EMAIL_HOST = get_env_value('EMAIL_HOST')
EMAIL_PORT = get_env_value('EMAIL_PORT')
EMAIL_USE_TLS = get_env_value('EMAIL_USE_TLS')
EMAIL_HOST_USER = get_env_value('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = get_env_value('EMAIL_HOST_PASSWORD')