# Generated by Django 3.2 on 2022-03-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('path', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('icon', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('search', models.BooleanField(default=False)),
                ('roles', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('divider', models.BooleanField(default=False)),
                ('no', models.IntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('idParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
    ]
