array = {
    'unit_pembangkit': {
        'examples': [
            {
                'id_unit_pembangkit': "",
                'nama_unit_pembangkit': 'UPK ASAM ASAM',
                'alamat': 'ASAM ASAM 1',
                'latitude': 0,
                'longitude': 0,
                'id_uid': '1',
                'id_up3_1': '2',
                'id_ulp_1': '3',
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_unit_pembangkit': "",
                'nama_unit_pembangkit': 'UPK ASAM ASAM #2',
                'alamat': 'ASAM ASAM 2',
                'latitude': 0,
                'longitude': 0,
                'id_uid': '1',
                'id_up3_1': '2',
                'id_ulp_1': '3',
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_unit_pembangkit': 3,
                'nama_unit_pembangkit': 'UPK ASAM ASAM #3',
                'alamat': 'ASAM ASAM 2 UPDATE ALAMAT',
                'latitude': 1,
                'longitude': 1,
                'id_uid': '1',
                'id_up3_1': '2',
                'id_ulp_1': '3',
                'status': 'inactive',
                'event_upload': 'UPDATE'
            },
            {
                'id_unit_pembangkit': 1,
                'nama_unit_pembangkit': 'UPK ASAM ASAM',
                'alamat': 'ASAM ASAM 1',
                'latitude': 0,
                'longitude': 0,
                'id_uid': '1',
                'id_up3_1': '2',
                'id_ulp_1': '3',
                'status': 'active',
                'event_upload': 'DELETE'
            },
            {
                'id_unit_pembangkit': 3,
                'nama_unit_pembangkit': 'UPK ASAM ASAM #3',
                'alamat': 'ASAM ASAM 3',
                'latitude': 0,
                'longitude': 0,
                'id_uid': '1',
                'id_up3_1': '2',
                'id_ulp_1': '3',
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_UNIT_PEMBANGKIT',
            'ALAMAT',
            'LATITUDE',
            'LONGITUDE',
            'STATUS',
            'ID_UID',
            'ID_UP3',
            'ID_ULP',
            'EVENT_UPLOAD'
        ]
    },
    'pembangkit': {
        'examples': [
            {
                'id_pembangkit': '',
                'nama_pembangkit': 'PEMBANGKIT CILEDUG',
                'alamat': 'KP KETAPANG PINANG',
                'id_parent_lokasi': '2',
                'id_ref_jenis_pembangkit': '2',
                'latitude': -6.2022725,
                'longitude': 106.6296399,
                # 'id_uid': '1',
                # 'id_up3_1': '2',
                # 'id_ulp_1': '3',
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_pembangkit': '',
                'nama_pembangkit': 'PEMBANGKIT SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 15810',
                'id_parent_lokasi': '2',
                'id_ref_jenis_pembangkit': '2',
                'latitude': -6.2022726,
                'longitude': 106.6296400,
                # 'id_uid': '1',
                # 'id_up3_1': '2',
                # 'id_ulp_1': '3',
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_pembangkit': 2,
                'nama_pembangkit': 'PEMBANGKIT SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_parent_lokasi': '2',
                'id_ref_jenis_pembangkit': '2',
                'latitude': -6.2022726,
                'longitude': 106.6296400,
                # 'id_uid': '1',
                # 'id_up3_1': '2',
                # 'id_ulp_1': '3',
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_pembangkit': '',
                'nama_pembangkit': 'PEMBANGKIT CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_parent_lokasi': '2',
                'id_ref_jenis_pembangkit': '2',
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                # 'id_uid': '1',
                # 'id_up3_1': '2',
                # 'id_ulp_1': '3',
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_pembangkit': 4,
                'nama_pembangkit': 'PEMBANGKIT CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_parent_lokasi': '2',
                'id_ref_jenis_pembangkit': '2',
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                # 'id_uid': '1',
                # 'id_up3_1': '2',
                # 'id_ulp_1': '3',
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_PEMBANGKIT',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'ID_UID',
            'ID_UP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'gardu_induk': {
        'examples': [
            {
                'id_gi': '',
                'kode_lokasi': 'T01',
                'nama_gi': 'CILEDUG',
                'alamat': 'KP KETAPANG PINANG',
                'id_parent_lokasi': '2',
                'latitude': -6.2022725,
                'longitude': 106.6296399,
                'id_up2b': '1', 
                'jenis_gi': 'GI',
                'fungsi_scada': 'FI',
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_gi': '',
                'kode_lokasi': '#T02',
                'nama_gi': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 15810',
                'id_parent_lokasi': '2',
                'latitude': -6.2022726,
                'longitude': 106.6296400,
                'id_up2b': '1', 
                'jenis_gi': 'GI',
                'fungsi_scada': 'FI',
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_gi': 2,
                'kode_lokasi': '#T03',
                'nama_gi': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_parent_lokasi': '2',
                'latitude': -6.2022726,
                'longitude': 106.6296400,
                'id_up2b': '1', 
                'jenis_gi': 'GI',
                'fungsi_scada': 'FI',
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_gi': '',
                'kode_lokasi': '#T04',
                'nama_gi': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_parent_lokasi': '2',
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'id_up2b': '1', 
                'jenis_gi': 'GI',
                'fungsi_scada': 'FI',
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_gi': 4,
                'kode_lokasi': '#T05',
                'nama_gi': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_parent_lokasi': '2',
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'id_up2b': '1', 
                'jenis_gi': 'GI',
                'fungsi_scada': 'FI',
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_GI',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'ID_UID',
            'ID_UP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'trafo_gi': {
        'examples': [
            {
                'id_trafo_gi': '',
                'nama_trafo_gi': 'CILEDUG',
                'alamat': 'KP KETAPANG PINANG',
                'id_parent_lokasi': '4',
                'kapasitas': '0',
                'sub_sistem': 'string',
                'pemilik': 'DISJABAR',
                'status_trafo': 'string',
                'jenis_trafo': 'PS',
                'i_max': '0',
                'ratio_ct': '0',
                'ratio_vt': '0',
                'fk_meter_pembanding': '0',
                'def_pengukuran_teg_primer': '150',
                'def_pengukuran_teg_sekunder': '20.5',
                'def_nilai_cosq': '0.95',
                'jenis_layanan': 'KTT',
                'sinkron_data': 'AMR',
                'id_i': '',
                'id_v': '',
                'id_p': '',
                'id_amr': '1',
                'id_portal_ext': '',
                'url_webservice': '',
                'latitude': -6.2022725,
                'longitude': 106.6296399,
                'coverage': 'TANGERANG, JAKARTA, DEPOK',
                'kva': 1,
                'phase': 3, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_trafo_gi': '',
                'nama_trafo_gi': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 15810',
                'id_parent_lokasi': '2',
                'kapasitas': '0',
                'sub_sistem': 'string',
                'pemilik': 'DISJABAR',
                'status_trafo': 'string',
                'jenis_trafo': 'DAYA',
                'i_max': '0',
                'ratio_ct': '0',
                'ratio_vt': '0',
                'fk_meter_pembanding': '0',
                'def_pengukuran_teg_primer': '150',
                'def_pengukuran_teg_sekunder': '20.5',
                'def_nilai_cosq': '0.95',
                'jenis_layanan': 'NON KTT',
                'sinkron_data': 'SCADA',
                'id_i': '1',
                'id_v': '1',
                'id_p': '1',
                'id_amr': '',
                'id_portal_ext': '',
                'url_webservice': '',
                'latitude': -6.2022726,
                'longitude': 106.6296400,
                'coverage': 'TANGERANG, JAKARTA, DEPOK',
                'kva': 1,
                'phase': 3, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_trafo_gi': 2,
                'nama_trafo_gi': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_parent_lokasi': '2',
                'kapasitas': '',
                'sub_sistem': '',
                'pemilik': 'DISJABAR',
                'status_trafo': '',
                'jenis_trafo': 'PS',
                'i_max': '',
                'ratio_ct': '',
                'ratio_vt': '',
                'fk_meter_pembanding': '',
                'def_pengukuran_teg_primer': '150',
                'def_pengukuran_teg_sekunder': '20.5',
                'def_nilai_cosq': '0.95',
                'jenis_layanan': 'NON KTT',
                'sinkron_data': 'PORTAL EXT',
                'id_i': '',
                'id_v': '',
                'id_p': '',
                'id_amr': '',
                'id_portal_ext': '1',
                'url_webservice': '1',
                'latitude': -6.2022726,
                'longitude': 106.6296400,
                'coverage': 'TANGERANG, JAKARTA, DEPOK',
                'kva': 1,
                'phase': 3, 
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_trafo_gi': '',
                'nama_trafo_gi': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_parent_lokasi': '2',
                'kapasitas': '0',
                'sub_sistem': 'string',
                'pemilik': 'DISJABAR',
                'status_trafo': 'string',
                'jenis_trafo': 'DAYA',
                'i_max': '0',
                'ratio_ct': '0',
                'ratio_vt': '0',
                'fk_meter_pembanding': '0',
                'def_pengukuran_teg_primer': '150',
                'def_pengukuran_teg_sekunder': '20.5',
                'def_nilai_cosq': '0.95',
                'jenis_layanan': 'NON KTT',
                'sinkron_data': '',
                'id_i': '',
                'id_v': '',
                'id_p': '',
                'id_amr': '',
                'id_portal_ext': '',
                'url_webservice': '',
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'coverage': 'TANGERANG, JAKARTA, DEPOK',
                'kva': 1,
                'phase': 3, 
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_trafo_gi': 4,
                'nama_trafo_gi': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_parent_lokasi': '2',
                'kapasitas': '0',
                'sub_sistem': 'string',
                'pemilik': 'DISJABAR',
                'status_trafo': 'string',
                'jenis_trafo': 'DAYA',
                'i_max': '0',
                'ratio_ct': '0',
                'ratio_vt': '0',
                'fk_meter_pembanding': '0',
                'def_pengukuran_teg_primer': '150',
                'def_pengukuran_teg_sekunder': '20.5',
                'def_nilai_cosq': '0.95',
                'jenis_layanan': 'KTT',
                'sinkron_data': 'AMR',
                'id_i': '',
                'id_v': '',
                'id_p': '',
                'id_amr': '1',
                'id_portal_ext': '',
                'url_webservice': '',
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'coverage': 'TANGERANG, JAKARTA, DEPOK',
                'kva': 1,
                'phase': 3, 
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_TRAFO_GI',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'COVERAGE',
            'KVA',
            'PHASE',
            'ID_UID',
            'ID_UP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'penyulang': {
        'examples': [
            {
                'id_penyulang': '',
                'kode_lokasi': 'F28',
                'nama_penyulang': 'CKUPA.F28',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_uid': '1',
                'id_up3_1': '1',
                'id_ulp': '1',
                'id_parent_lokasi': '4',
                'jenis_jaringan': 'CAMPURAN',
                'status_penyulang': 'BERBEBAN', 
                'pemilik': 'DISJABAR',
                'i_max': 0,
                'dcc': 0,
                'ratio_ct': 0,
                'ratio_vt': 0,
                'faktor_kali': 0,
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'kva': 0,
                'phase': 0, 
                'no_urut': 1,  
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_penyulang': '',
                'kode_lokasi': 'F32', 
                'nama_penyulang': 'CKUPA.F32',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_uid': '1',
                'id_up3_1': '1',
                'id_ulp': '1',
                'id_parent_lokasi': '4',
                'jenis_jaringan': 'SKTM',
                'status_penyulang': 'EXPRESS', 
                'pemilik': 'DISJABAR',
                'i_max': 0,
                'dcc': 0,
                'ratio_ct': 0,
                'ratio_vt': 0,
                'faktor_kali': 0,
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'kva': 0,
                'phase': 0, 
                'no_urut': 2,  
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_penyulang': '',
                'kode_lokasi': 'F07',  
                'nama_penyulang': 'MLNUM.F07',
                'alamat': 'Kawasan Industri Millenium',
                'id_uid': '1',
                'id_up3_1': '1',
                'id_ulp': '1',
                'id_parent_lokasi': '4',
                'jenis_jaringan': 'SUTM',
                'status_penyulang': 'PEMBANGKIT', 
                'pemilik': 'DISJABAR',
                'i_max': 0,
                'dcc': 0,
                'ratio_ct': 0,
                'ratio_vt': 0,
                'faktor_kali': 0,
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'kva': 0,
                'phase': 0, 
                'no_urut': 3,  
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_penyulang': '2',
                'kode_lokasi': 'F322',   
                'nama_penyulang': 'CKUPA.F322',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_uid': '1',
                'id_up3_1': '1',
                'id_ulp': '1',
                'id_parent_lokasi': '4',
                'jenis_jaringan': 'SUTM',
                'status_penyulang': 'SPOTILOAD', 
                'pemilik': 'DISJABAR',
                'i_max': 0,
                'dcc': 0,
                'ratio_ct': 0,
                'ratio_vt': 0,
                'faktor_kali': 0,
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'kva': 0,
                'phase': 0, 
                'no_urut': 4,  
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_penyulang': '2',
                'kode_lokasi': 'F322',    
                'nama_penyulang': 'CKUPA.F322',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_uid': '1',
                'id_up3_1': '1',
                'id_ulp': '1',
                'id_parent_lokasi': '4',
                'jenis_jaringan': 'CAMPURAN',
                'status_penyulang': 'EXPRESS BERBEBAN', 
                'pemilik': 'DISJABAR',
                'i_max': 0,
                'dcc': 0,
                'ratio_ct': 0,
                'ratio_vt': 0,
                'faktor_kali': 0,
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'kva': 0,
                'phase': 0, 
                'no_urut': 5,  
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_penyulang': '2',
                'kode_lokasi': 'CKUPA.F322', 
                'nama_penyulang': 'CKUPA.F322',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_uid': '1',
                'id_up3_1': '1',
                'id_ulp': '1',
                'id_parent_lokasi': '4',
                'jenis_jaringan': 'CAMPURAN',
                'status_penyulang': 'BERBEBAN', 
                'pemilik': 'DISJABAR',
                'i_max': 0,
                'dcc': 0,
                'ratio_ct': 0,
                'ratio_vt': 0,
                'faktor_kali': 0,
                'latitude': -6.2022727,
                'longitude': 106.6296401,
                'kva': 0,
                'phase': 0, 
                'no_urut': 65,  
                'status': 'active', 
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_PENYULANG',
            'ALAMAT',
            'ID_REF_LOKASI',
            'COVERAGE',
            'JENIS_JARINGAN',
            'STATUS_PENYULANG',
            'NO_TIANG',
            'ID_UID',
            'ID_ULP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ],
        'status_penyulang': [
            'BERBEBAN',
            'EXPRESS',
            'EXPRESS BERBEBAN',
            'INCOMING',
            'KOPEL',
            'PEMBANGKIT',
            'SPARE',
            'SPOTLOAD',
            'STR'
        ]
    },
    'zona': {
        'examples': [
            {
                'id_zona': '',
                'nama_zona': '56.CKUPA.F28.Z01',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_parent_lokasi': '4',
                'latitude': -6.2022725,
                'longitude': 106.6296399, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_zona': '',
                'nama_zona': '56.CKUPA.F32.Z02',
                'alamat': 'Jln. Raya Pasar K',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_zona': 2,
                'nama_zona': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_zona': '',
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_parent_lokasi': '4',
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_zona': 4,
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_parent_lokasi': '4',
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_ZONA',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'COVERAGE',
            'KVA',
            'PHASE',
            'ID_UID',
            'ID_ULP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'section': {
        'examples': [
             {
                'id_section': '',
                'nama_zona': '56.CKUPA.F28.Z01',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022725,
                'longitude': 106.6296399, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_section': '',
                'nama_zona': '56.CKUPA.F32.Z02',
                'alamat': 'Jln. Raya Pasar K',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_section': 2,
                'nama_zona': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_section': '',
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_section': 4,
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_parent_lokasi': '4', 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_SECTION',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'COVERAGE',
            'KVA',
            'PHASE',
            'ID_UID',
            'ID_ULP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'segment': {
        'examples': [
            {
                'id_segment': '',
                'nama_zona': '56.CKUPA.F28.Z01',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'latitude': -6.2022725,
                'longitude': 106.6296399, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_segment': '',
                'nama_zona': '56.CKUPA.F32.Z02',
                'alamat': 'Jln. Raya Pasar K',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_segment': 2,
                'nama_zona': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_segment': '',
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_segment': 4,
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_SEGMENT',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'COVERAGE',
            'KVA',
            'PHASE',
            'ID_UID',
            'ID_ULP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'gardu_distribusi': {
        'examples': [
             {
                'id_gardu_distribusi': '',
                'nama_zona': '56.CKUPA.F28.Z01',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'no_tiang':'234', 
                'latitude': -6.2022725,
                'longitude': 106.6296399, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_gardu_distribusi': '',
                'nama_zona': '56.CKUPA.F32.Z02',
                'alamat': 'Jln. Raya Pasar K',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'no_tiang':'234', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_gardu_distribusi': 2,
                'nama_zona': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'no_tiang':'234', 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_gardu_distribusi': '',
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'no_tiang':'234', 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_gardu_distribusi': 4,
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'no_tiang':'234', 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_GARDU_DISTRIBUSI',
            'ALAMAT',
            'LATITUDE',
            'LONGITUDE',
            'STATUS',
            'NO_TIANG',
            'ID_PENYULANG',
            'ID_ZONE',
            'ID_SECTION',
            'ID_SEGMENT',
            'ID_UID',
            'ID_ULP3',
            'ID_ULP',
            'EVENT_UPLOAD'
        ]
    },
    'trafo_gd': {
        'examples': [
            {
                'id_trafo_gd': '',
                'nama_zona': '56.CKUPA.F28.Z01',
                'alamat': 'Jln. Raya Pasar Kemis Pasir Gadung, Tangerang',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'id_gardu_distribusi': 4, 
                'latitude': -6.2022725,
                'longitude': 106.6296399, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_trafo_gd': '',
                'nama_zona': '56.CKUPA.F32.Z02',
                'alamat': 'Jln. Raya Pasar K',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'id_gardu_distribusi': 4, 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_trafo_gd': 2,
                'nama_zona': 'SUMMARECON GADING SERPONG',
                'alamat': 'Gg. H. Rafiudin, Pakulonan Bar., Kec. Klp. Dua, Tangerang, Banten 2022201',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'id_gardu_distribusi': 4, 
                'latitude': -6.2022726,
                'longitude': 106.6296400, 
                'status': 'active',
                'event_upload': 'UPDATE'
            },
            {
                'id_trafo_gd': '',
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'id_gardu_distribusi': 4, 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'INSERT'
            },
            {
                'id_trafo_gd': 4,
                'nama_zona': 'CILEGON BARU',
                'alamat': 'CILEGON BARU',
                'id_gardu_induk': '1',
                'id_trafo_gi': '3', 
                'id_penyulang': '4', 
                'id_zone': '4', 
                'id_section': '4', 
                'id_segment': '5',
                'id_gardu_distribusi': 4, 
                'latitude': -6.2022727,
                'longitude': 106.6296401, 
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_TRAFO_GD',
            'ALAMAT',
            'ID_REF_LOKASI',
            'LATITUDE',
            'LONGITUDE',
            'COVERAGE',
            'KVA',
            'PHASE',
            'ID_UID',
            'ID_ULP3',
            'ID_ULP',
            'STATUS',
            'EVENT_UPLOAD'
        ]
    },
    'kantor': {
        'examples': [
            {
                'id_kantor': "",
                'nama_kantor': 'GH',
                'id_jenis_kantor': 1,
                'id_unit_induk': 1,
                'alamat': 'ASAM ASAM 1',
                'latitude': 0,
                'longitude': 0, 
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_kantor': "",
                'nama_kantor': 'GH #2',
                'id_jenis_kantor': 1,
                'id_unit_induk': 1,
                'alamat': 'ASAM ASAM 2',
                'latitude': 0,
                'longitude': 0,
                'status': 'active',
                'event_upload': 'INSERT'
            },
            {
                'id_kantor': 3,
                'nama_kantor': 'GH #3',
                'id_jenis_kantor': 1,
                'id_unit_induk': 1,
                'alamat': 'ASAM ASAM 2 UPDATE ALAMAT',
                'latitude': 1,
                'longitude': 1,
                'status': 'inactive',
                'event_upload': 'UPDATE'
            },
            {
                'id_kantor': 1,
                'nama_kantor': 'GH',
                'id_jenis_kantor': 1,
                'id_unit_induk': 1,
                'alamat': 'ASAM ASAM 1',
                'latitude': 0,
                'longitude': 0,
                'status': 'active',
                'event_upload': 'DELETE'
            },
            {
                'id_kantor': 3,
                'nama_kantor': 'GH #3',
                'id_jenis_kantor': 1,
                'id_unit_induk': 1,
                'alamat': 'ASAM ASAM 3',
                'latitude': 0,
                'longitude': 0,
                'status': 'inactive',
                'event_upload': 'DELETE'
            },
        ],
        'headers': [
            'NAMA_UNIT_PEMBANGKIT',
            'ALAMAT',
            'LATITUDE',
            'LONGITUDE',
            'STATUS',
            'ID_UID',
            'ID_UP3',
            'ID_ULP',
            'EVENT_UPLOAD'
        ]
    },
}

def template(name):
    try:
        newarray = array.get(f'{name}', [])
        return newarray
    except ValueError:
        return 'not found'

def status_listrik(status):
    if status == 'active':
        return 1
    elif status == 'inactive':
        return 0

def fillnan(value): 
    return value if value != 'nan' else None 