
array = {
    'test': {
        'view': "Berhasil mendapatkan data test",
        'create': "Tambah data test berhasil",
        'update': "Ubah data test berhasil",
        'delete': "Data test berhasil dihapus",
        'not_found': "Data test tidak ditemukan",
    },
    'auth': {
        'view': "Berhasil mendapatkan data auth",
        'create': "Tambah data auth berhasil",
        'update': "Ubah data auth berhasil",
        'delete': "Data auth berhasil dihapus",
        'not_found': "Data auth tidak ditemukan",
    },
    'users': {
        'view': "Berhasil mendapatkan data user",
        'create': "Tambah data user berhasil",
        'update': "Ubah data user berhasil",
        'update_regu': "Ubah data Regu user berhasil",
        'delete': "Data user berhasil dihapus",
        'delete_regu': "Regu user berhasil dihapus",
        'not_found': "Data user tidak ditemukan",
        'update_password': "Ubah password user berhasil.",
        'update_password_old_notmatch': "Password lama salah.",
        'update_password_notmatch': "New password dan retype new password tidak sama.",
        'update_password_failed': "Ubah password user gagal.",
        'update_password_field': "Tolong isi field: old_password, new_password, retype_new_password",
        'reset_password_field': "Tolong isi field: new_password",
    },
    'roles': {
        'view': "Berhasil mendapatkan data roles",
        'create': "Tambah data roles berhasil",
        'update': "Ubah data roles berhasil",
        'delete': "Data roles berhasil dihapus",
        'not_found': "Data roles tidak ditemukan",
    },
    'menu': {
        'view': "Berhasil mendapatkan data menu",
        'create': "Tambah data menu berhasil",
        'update': "Ubah data menu berhasil",
        'update_failed': "Ubah data menu gagal",
        'delete': "Data menu berhasil dihapus",
        'not_found': "Data menu tidak ditemukan",
    },
    'ref_lokasi': {
        'view': "Berhasil mendapatkan data ref_lokasi",
        'create': "Tambah data ref_lokasi berhasil",
        'update': "Ubah data ref_lokasi berhasil",
        'delete': "Data ref_lokasi berhasil dihapus",
        'not_found': "Data ref_lokasi tidak ditemukan",
    },
    'ref_lokasi_gd': {
        'view': "Berhasil mendapatkan data ref_lokasi_gd",
        'create': "Tambah data ref_lokasi_gd berhasil",
        'update': "Ubah data ref_lokasi_gd berhasil",
        'delete': "Data ref_lokasi_gd berhasil dihapus",
        'not_found': "Data ref_lokasi_gd tidak ditemukan",
    },
    'ref_jenis_lokasi': {
        'view': "Berhasil mendapatkan data ref_jenis_lokasi",
        'create': "Tambah data ref_jenis_lokasi berhasil",
        'update': "Ubah data ref_jenis_lokasi berhasil",
        'delete': "Data ref_jenis_lokasi berhasil dihapus",
        'not_found': "Data ref_jenis_lokasi tidak ditemukan",
    },
    'ref_aset': {
        'view': "Berhasil mendapatkan data ref_aset",
        'create': "Tambah data ref_aset berhasil",
        'update': "Ubah data ref_aset berhasil",
        'delete': "Data ref_aset berhasil dihapus",
        'not_found': "Data ref_aset tidak ditemukan",
    },
    'ref_aset_jenis': {
        'view': "Berhasil mendapatkan data ref_aset_jenis",
        'create': "Tambah data ref_aset_jenis berhasil",
        'update': "Ubah data ref_aset_jenis berhasil",
        'delete': "Data ref_aset_jenis berhasil dihapus",
        'not_found': "Data ref_aset_jenis tidak ditemukan",
    },
    'ref_aset_manufaktur': {
        'view': "Berhasil mendapatkan data ref_aset_manufaktur",
        'create': "Tambah data ref_aset_manufaktur berhasil",
        'update': "Ubah data ref_aset_manufaktur berhasil",
        'delete': "Data ref_aset_manufaktur berhasil dihapus",
        'not_found': "Data ref_aset_manufaktur tidak ditemukan",
    },
    'ref_aset_lantai': {
        'view': "Berhasil mendapatkan data ref_aset_lantai",
        'create': "Tambah data ref_aset_lantai berhasil",
        'update': "Ubah data ref_aset_lantai berhasil",
        'delete': "Data ref_aset_lantai berhasil dihapus",
        'not_found': "Data ref_aset_lantai tidak ditemukan",
    },
    'ref_aset_ruangan': {
        'view': "Berhasil mendapatkan data ref_aset_ruangan",
        'create': "Tambah data ref_aset_ruangan berhasil",
        'update': "Ubah data ref_aset_ruangan berhasil",
        'delete': "Data ref_aset_ruangan berhasil dihapus",
        'not_found': "Data ref_aset_ruangan tidak ditemukan",
    },
    'ref_aset_rak': {
        'view': "Berhasil mendapatkan data ref_aset_rak",
        'create': "Tambah data ref_aset_rak berhasil",
        'update': "Ubah data ref_aset_rak berhasil",
        'delete': "Data ref_aset_rak berhasil dihapus",
        'not_found': "Data ref_aset_rak tidak ditemukan",
    },
    'ref_aset_kondisi': {
        'view': "Berhasil mendapatkan data ref_aset_kondisi",
        'create': "Tambah data ref_aset_kondisi berhasil",
        'update': "Ubah data ref_aset_kondisi berhasil",
        'delete': "Data ref_aset_kondisi berhasil dihapus",
        'not_found': "Data ref_aset_kondisi tidak ditemukan",
    },
    'ref_aset_level': {
        'view': "Berhasil mendapatkan data ref_aset_level",
        'create': "Tambah data ref_aset_level berhasil",
        'update': "Ubah data ref_aset_level berhasil",
        'delete': "Data ref_aset_level berhasil dihapus",
        'not_found': "Data ref_aset_level tidak ditemukan",
    },
    'ref_aset_status': {
        'view': "Berhasil mendapatkan data ref_aset_status",
        'create': "Tambah data ref_aset_status berhasil",
        'update': "Ubah data ref_aset_status berhasil",
        'delete': "Data ref_aset_status berhasil dihapus",
        'not_found': "Data ref_aset_status tidak ditemukan",
    },
    'ref_aset_jenis_mutasi': {
        'view': "Berhasil mendapatkan data ref_aset_jenis_mutasi",
        'create': "Tambah data ref_aset_jenis_mutasi berhasil",
        'update': "Ubah data ref_aset_jenis_mutasi berhasil",
        'delete': "Data ref_aset_jenis_mutasi berhasil dihapus",
        'not_found': "Data ref_aset_jenis_mutasi tidak ditemukan",
    },
    'ref_aset_doc': {
        'view': "Berhasil mendapatkan data ref_aset_doc",
        'create': "Tambah data ref_aset_doc berhasil",
        'update': "Ubah data ref_aset_doc berhasil",
        'delete': "Data ref_aset_doc berhasil dihapus",
        'not_found': "Data ref_aset_doc tidak ditemukan",
    },
    'ref_aset_ext_atr': {
        'view': "Berhasil mendapatkan data ref_aset_ext_atr",
        'create': "Tambah data ref_aset_ext_atr berhasil",
        'update': "Ubah data ref_aset_ext_atr berhasil",
        'delete': "Data ref_aset_ext_atr berhasil dihapus",
        'not_found': "Data ref_aset_ext_atr tidak ditemukan",
        'update_failed': "Update data ref_aset_ext_atr tidak berhasil",
    },
    'ref_aset_ex_atr': {
        'view': "Berhasil mendapatkan data ref_aset_ex_atr",
        'create': "Tambah data ref_aset_ex_atr berhasil",
        'update': "Ubah data ref_aset_ex_atr berhasil",
        'delete': "Data ref_aset_ex_atr berhasil dihapus",
        'not_found': "Data ref_aset_ex_atr tidak ditemukan",
    },
    'tree_jaringan': {
        'view': "Berhasil mendapatkan data tree_jaringan",
        'create': "Tambah data tree_jaringan berhasil",
        'update': "Ubah data tree_jaringan berhasil",
        'update_failed': "Ubah data tree_jaringan gagal",
        'delete': "Data tree_jaringan berhasil dihapus",
        'not_found': "Data tree_jaringan tidak ditemukan",
    },
    'ref_hi': {
        'view': "Berhasil mendapatkan data ref_hi",
        'create': "Tambah data ref_hi berhasil",
        'update': "Ubah data ref_hi berhasil",
        'delete': "Data ref_hi berhasil dihapus",
        'not_found': "Data ref_hi tidak ditemukan",
    },
    'ref_pm': {
        'view': "Berhasil mendapatkan data ref_pm",
        'create': "Tambah data ref_pm berhasil",
        'update': "Ubah data ref_pm berhasil",
        'delete': "Data ref_pm berhasil dihapus",
        'not_found': "Data ref_pm tidak ditemukan",
    },
    'ref_pm_detail': {
        'view': "Berhasil mendapatkan data ref_pm_detail",
        'create': "Tambah data ref_pm_detail berhasil",
        'update': "Ubah data ref_pm_detail berhasil",
        'delete': "Data ref_pm_detail berhasil dihapus",
        'not_found': "Data ref_pm_detail tidak ditemukan",
    },
    'ref_pm_detail_logic': {
        'view': "Berhasil mendapatkan data ref_pm_detail_logic",
        'create': "Tambah data ref_pm_detail_logic berhasil",
        'update': "Ubah data ref_pm_detail_logic berhasil",
        'delete': "Data ref_pm_detail_logic berhasil dihapus",
        'not_found': "Data ref_pm_detail_logic tidak ditemukan",
    },
    'ref_wo_jenis': {
        'view': "Berhasil mendapatkan data ref_wo_jenis",
        'create': "Tambah data ref_wo_jenis berhasil",
        'update': "Ubah data ref_wo_jenis berhasil",
        'delete': "Data ref_wo_jenis berhasil dihapus",
        'not_found': "Data ref_wo_jenis tidak ditemukan",
    },
    'ref_wo_status': {
        'view': "Berhasil mendapatkan data ref_wo_status",
        'create': "Tambah data ref_wo_status berhasil",
        'update': "Ubah data ref_wo_status berhasil",
        'delete': "Data ref_wo_status berhasil dihapus",
        'not_found': "Data ref_wo_status tidak ditemukan",
    },
    'ref_kel_pekerjaan': {
        'view': "Berhasil mendapatkan data ref kelengkapan pekerjaan",
        'create': "Tambah data ref kelengkapan pekerjaan berhasil",
        'update': "Ubah data ref kelengkapan pekerjaan berhasil",
        'delete': "Data ref kelengkapan pekerjaan berhasil dihapus",
        'not_found': "Data ref kelengkapan pekerjaan tidak ditemukan",
    },
    'ref_kel_keselamatan': {
        'view': "Berhasil mendapatkan data ref kelengkapan keselamatan",
        'create': "Tambah data ref kelengkapan keselamatan berhasil",
        'update': "Ubah data ref kelengkapan keselamatan berhasil",
        'delete': "Data ref kelengkapan keselamatan berhasil dihapus",
        'not_found': "Data ref kelengkapan keselamatan tidak ditemukan",
    },
    'pertanyaan_qrc': {
        'view': "Berhasil mendapatkan data Pertanyaan QRC",
        'create': "Tambah data Pertanyaan QRC berhasil",
        'update': "Ubah data Pertanyaan QRC berhasil",
        'delete': "Data Pertanyaan QRC berhasil dihapus",
        'not_found': "Data Pertanyaan QRC tidak ditemukan",
    },
    'risk_point_qrc': {
        'view': "Berhasil mendapatkan data Risk Point QRC",
        'create': "Tambah data Risk Point QRC berhasil",
        'update': "Ubah data Risk Point QRC berhasil",
        'delete': "Data Risk Point QRC berhasil dihapus",
        'not_found': "Data Risk Point QRC tidak ditemukan",
    },
    'larangan_tanggung_jawab_mitra': {
        'view': "Berhasil mendapatkan data Larangan & Tanggung Jawab Mitra",
        'create': "Tambah data Larangan & Tanggung Jawab Mitra berhasil",
        'update': "Ubah data Larangan & Tanggung Jawab Mitra berhasil",
        'delete': "Data Larangan & Tanggung Jawab Mitra berhasil dihapus",
        'not_found': "Data Larangan & Tanggung Jawab Mitra tidak ditemukan",
    },
    'departemen': {
        'view': "Berhasil mendapatkan data Departemen",
        'create': "Tambah data Departemen berhasil",
        'update': "Ubah data Departemen",
        'delete': "Data Departemen berhasil dihapus",
        'not_found': "Data Departemen tidak ditemukan",
    },
    'jabatan': {
        'view': "Berhasil mendapatkan data Jabatan",
        'create': "Tambah data Jabatan berhasil",
        'update': "Ubah data Jabatan",
        'delete': "Data Jabatan berhasil dihapus",
        'not_found': "Data Jabatan tidak ditemukan",
    },
    'perusahaan': {
        'view': "Berhasil mendapatkan data Perusahaan",
        'create': "Tambah data Perusahaan berhasil",
        'update': "Ubah data Perusahaan",
        'delete': "Data Perusahaan berhasil dihapus",
        'not_found': "Data Perusahaan tidak ditemukan",
    },
    'trans_pm_jenis_doc': {
        'view': "Berhasil mendapatkan data trans_pm_jenis_doc",
        'create': "Tambah data trans_pm_jenis_doc berhasil",
        'update': "Ubah data trans_pm_jenis_doc",
        'delete': "Data trans_pm_jenis_doc berhasil dihapus",
        'not_found': "Data trans_pm_jenis_doc tidak ditemukan",
    },
    'trans_pm_photo': {
        'view': "Berhasil mendapatkan data trans_pm_photo",
        'create': "Tambah data trans_pm_photo berhasil",
        'update': "Ubah data trans_pm_photo",
        'delete': "Data trans_pm_photo berhasil dihapus",
        'not_found': "Data trans_pm_photo tidak ditemukan",
    },
    'trans_wo': {
        'view': "Berhasil mendapatkan data trans_wo",
        'create': "Tambah data trans_wo berhasil",
        'update': "Ubah data trans_wo",
        'delete': "Data trans_wo berhasil dihapus",
        'not_found': "Data trans_wo tidak ditemukan",
    },
    'trans_wo_log_status': {
        'view': "Berhasil mendapatkan data trans_wo_log_status",
        'create': "Tambah data trans_wo_log_status berhasil",
        'update': "Ubah data trans_wo_log_status",
        'delete': "Data trans_wo_log_status berhasil dihapus",
        'not_found': "Data trans_wo_log_status tidak ditemukan",
    },
    'fasop_path_1': {
        'view': "Berhasil mendapatkan data Fasop Path 1",
        'create': "Tambah data Fasop Path 1 berhasil",
        'update': "Ubah data Fasop Path 1",
        'delete': "Data Fasop Path 1 berhasil dihapus",
        'not_found': "Data Fasop Path 1 tidak ditemukan",
    },
    'fasop_path_3': {
        'view': "Berhasil mendapatkan data Fasop Path 3",
        'create': "Tambah data Fasop Path 3 berhasil",
        'update': "Ubah data Fasop Path 3",
        'delete': "Data Fasop Path 3 berhasil dihapus",
        'not_found': "Data Fasop Path 3 tidak ditemukan", 
    },
    'fasop_pm': {
        'view': "Berhasil mendapatkan data Fasop PM",
        'create': "Tambah data Fasop PM berhasil",
        'update': "Ubah data Fasop PM",
        'delete': "Data Fasop PM berhasil dihapus",
        'not_found': "Data Fasop PM tidak ditemukan",
    },
    'fasop_point_type': {
        'view': "Berhasil mendapatkan data Master Fasop Point Type",
        'create': "Tambah data Master Fasop Point Type berhasil",
        'update': "Ubah data Master Fasop Point Type",
        'delete': "Data Master Fasop Point Type berhasil dihapus",
        'not_found': "Data Master Fasop Point Type tidak ditemukan",
    },
    'fasop_point_type_state': {
        'view': "Berhasil mendapatkan data Master Fasop Point Type State",
        'create': "Tambah data Master Fasop Point Type State berhasil",
        'update': "Ubah data Master Fasop Point Type State",
        'delete': "Data Master Fasop Point Type State berhasil dihapus",
        'not_found': "Data Master Fasop Point Type State tidak ditemukan",
    },
    'telegram_bot': {
        'view': "Berhasil mendapatkan data Master Fasop Telegram Bot",
        'create': "Tambah data Master Fasop  Telegram Bot berhasil",
        'update': "Ubah data Master Fasop  Telegram Bot",
        'delete': "Data Master Fasop Telegram Bot berhasil dihapus",
        'not_found': "Data Master Fasop Telegram Bot tidak ditemukan",
    },
    'telegram_group': {
        'view': "Berhasil mendapatkan data Master Fasop Telegram Group",
        'create': "Tambah data Master Fasop  Telegram Group berhasil",
        'update': "Ubah data Master Fasop  Telegram Group",
        'delete': "Data Master Fasop Telegram Group berhasil dihapus",
        'not_found': "Data Master Fasop Telegram Group tidak ditemukan",
    },
    'telegram_log': {
        'view': "Berhasil mendapatkan data Master Fasop Telegram Log",
        'create': "Tambah data Master Fasop Telegram Log berhasil",
        'update': "Ubah data Master Fasop Telegram Log",
        'delete': "Data Master Fasop Telegram Log berhasil dihapus",
        'not_found': "Data Master Fasop Telegram Log tidak ditemukan",
    },
    'c_point': {
        'view': "Berhasil mendapatkan data Master Fasop C Point",
        'create': "Tambah data Master Fasop C Point berhasil",
        'update': "Ubah data Master Fasop C Point",
        'delete': "Data Master Fasop C Point berhasil dihapus",
        'not_found': "Data Master Fasop C Point tidak ditemukan",
    },
    'fasop_rtu': {
        'view': "Berhasil mendapatkan data Master Fasop Master RTU",
        'create': "Tambah data Master Fasop Master RTU berhasil",
        'update': "Ubah data Master Fasop Master RTU",
        'delete': "Data Master Fasop Master RTU berhasil dihapus",
        'not_found': "Data Master Fasop Master RTU tidak ditemukan",
    },
    'opsisdis_jenis_penyebab_gangguan': {
        'view': "Berhasil mendapatkan data Jenis Penyebab Gangguan",
        'create': "Tambah data Jenis Penyebab Gangguan berhasil",
        'update': "Ubah data Jenis Penyebab Gangguan",
        'delete': "Data Jenis Penyebab Gangguan berhasil dihapus",
        'not_found': "Data Jenis Penyebab Gangguan tidak ditemukan",
    },
    'opsisdis_penyebab_gangguan': {
        'view': "Berhasil mendapatkan data Penyebab Gangguan",
        'create': "Tambah data Penyebab Gangguan berhasil",
        'update': "Ubah data Penyebab Gangguan",
        'delete': "Data Penyebab Gangguan berhasil dihapus",
        'not_found': "Data Penyebab Gangguan tidak ditemukan",
    },
    'opsisdis_frekuensi': {
        'view': "Berhasil mendapatkan data Frekuensi",
        'create': "Tambah data Frekuensi berhasil",
        'update': "Ubah data Frekuensi",
        'delete': "Data Frekuensi berhasil dihapus",
        'not_found': "Data Frekuensi tidak ditemukan",
    },
    'approval_management_wp': {
        'view': "Berhasil mendapatkan data Approval Management WP",
        'create': "Tambah data Approval Management WP berhasil",
        'update': "Ubah data Approval Management WP",
        'delete': "Data Approval Management WP berhasil dihapus",
        'not_found': "Data Approval Management WP tidak ditemukan",
    },
    'fasop_master': {
        'view': "Berhasil mendapatkan data Fasop Master",
        'create': "Tambah data Fasop Master berhasil",
        'update': "Ubah data Fasop Master",
        'delete': "Data Fasop Master berhasil dihapus",
        'not_found': "Data Fasop Master tidak ditemukan",
    },
    'ext_user_token': {
        'view': "Berhasil mendapatkan data User Token",
        'create': "Tambah data UExt ser Token berhasil",
        'update_add': "Berhasil mendapatkan data User Token",
        'update': "Ubah data Ext User Token Berhasil",
        'delete': "Data Ext User Token berhasil dihapus",
        'not_found': "Data Ext User Token tidak ditemukan",
    },
    'ext_user_token_role': {
        'view': "Berhasil mendapatkan data Ext User Token Role",
        'create': "Tambah data Ext User Token Role berhasil",
        'update': "Ubah data Ext User Token Role Berhasil",
        'delete': "Data Ext User Token Role berhasil dihapus",
        'not_found': "Data Ext User Token Role tidak ditemukan",
    },
    'ext_module': {
        'view': "Berhasil mendapatkan data Ext Module",
        'create': "Tambah data Ext Module berhasil",
        'update': "Ubah data Ext Module Berhasil",
        'delete': "Data Ext Module berhasil dihapus",
        'not_found': "Data Ext Module tidak ditemukan",
    },
    'telemetring_pembangkit': {
        'view': "Berhasil mendapatkan data opsisdis telemetring pembangkit",
        'create': "Tambah data opsisdis telemetring pembangkit berhasil",
        'update': "Ubah data opsisdis telemetring pembangkit berhasil",
        'update_failed': "Ubah data opsisdis telemetring pembangkit gagal",
        'delete': "Data opsisdis telemetring pembangkit berhasil dihapus",
        'not_found': "Data opsisdis telemetring pembangkit tidak ditemukan",
        'not_child': ", tidak ada data yang tergenerate.",
    },
    'telemetring_trafo_gi': {
        'view': "Berhasil mendapatkan data opsisdis telemetring trafo gi",
        'create': "Tambah data opsisdis telemetring trafo gi berhasil",
        'update': "Ubah data opsisdis telemetring trafo gi berhasil",
        'update_failed': "Ubah data opsisdis telemetring trafo gi gagal",
        'delete': "Data opsisdis telemetring trafo gi berhasil dihapus",
        'not_found': "Data opsisdis telemetring trafo gi tidak ditemukan",
        'not_child': ", tidak ada data yang tergenerate.",
    },
    'telemetring_penyulang': {
        'view': "Berhasil mendapatkan data opsisdis telemetring penyulang",
        'create': "Tambah data opsisdis telemetring penyulang berhasil",
        'update': "Ubah data opsisdis telemetring penyulang berhasil",
        'update_failed': "Ubah data opsisdis telemetring penyulang gagal",
        'delete': "Data opsisdis telemetring penyulang berhasil dihapus",
        'not_found': "Data opsisdis telemetring penyulang tidak ditemukan",
        'not_child': ", tidak ada data yang tergenerate.",
    },
    'telemetring_zona': {
        'view': "Berhasil mendapatkan data opsisdis telemetring zona",
        'create': "Tambah data opsisdis telemetring zona berhasil",
        'update': "Ubah data opsisdis telemetring zona berhasil",
        'update_failed': "Ubah data opsisdis telemetring zona gagal",
        'delete': "Data opsisdis telemetring zona berhasil dihapus",
        'not_found': "Data opsisdis telemetring zona tidak ditemukan",
        'not_child': "Parent tidak memiliki Child Zona",
    },
    'telemetring_area': {
        'view': "Berhasil mendapatkan data opsisdis telemetring area",
        'create': "Tambah data opsisdis telemetring area berhasil",
        'update': "Ubah data opsisdis telemetring area berhasil",
        'update_failed': "Ubah data opsisdis telemetring area gagal",
        'delete': "Data opsisdis telemetring area berhasil dihapus",
        'not_found': "Data opsisdis telemetring area tidak ditemukan",
    },
    'telemetring_wilayah': {
        'view': "Berhasil mendapatkan data opsisdis telemetring wilayah",
        'create': "Tambah data opsisdis telemetring wilayah berhasil",
        'update': "Ubah data opsisdis telemetring wilayah berhasil",
        'update_failed': "Ubah data opsisdis telemetring wilayah gagal",
        'delete': "Data opsisdis telemetring wilayah berhasil dihapus",
        'not_found': "Data opsisdis telemetring wilayah tidak ditemukan",
    },
    'telemetring_amr_customer': {
        'view': "Berhasil mendapatkan data opsisdis telemetring AMR Energi",
        'create': "Tambah data opsisdis telemetring AMR Customer berhasil",
        'update': "Ubah data opsisdis telemetring AMR Customer berhasil",
        'update_failed': "Ubah data opsisdis telemetring AMR Customer gagal",
        'delete': "Data opsisdis telemetring AMR Customer berhasil dihapus",
        'not_found': "Data opsisdis telemetring AMR Customer tidak ditemukan",
    },
    'telemetring_amr_energi': {
        'view': "Berhasil mendapatkan data opsisdis telemetring AMR Energi",
        'create': "Tambah data opsisdis telemetring AMR Energi berhasil",
        'update': "Ubah data opsisdis telemetring AMR Energi berhasil",
        'update_failed': "Ubah data opsisdis telemetring AMR Energi gagal",
        'delete': "Data opsisdis telemetring AMR Energi berhasil dihapus",
        'not_found': "Data opsisdis telemetring AMR Energi tidak ditemukan",
    },
    'telemetring_amr_load_profile': {
        'view': "Berhasil mendapatkan data opsisdis telemetring AMR Load Profile",
        'create': "Tambah data opsisdis telemetring AMR Load Profile berhasil",
        'update': "Ubah data opsisdis telemetring AMR Load Profile berhasil",
        'update_failed': "Ubah data opsisdis telemetring AMR Load Profile gagal",
        'delete': "Data opsisdis telemetring AMR Load Profile berhasil dihapus",
        'not_found': "Data opsisdis telemetring AMR Load Profile tidak ditemukan",
    },
    'trans_jadwal_har': {
        'view': "Berhasil mendapatkan data opsisdis Jadwal Pemeliharaan Har",
        'create': "Tambah data opsisdis Jadwal Pemeliharaan Har berhasil",
        'update': "Ubah data opsisdis Jadwal Pemeliharaan Har berhasil",
        'create_failed': "Tambah data opsisdis Jadwal Pemeliharaan Har gagal",
        'update_failed': "Ubah data opsisdis Jadwal Pemeliharaan Har gagal",
        'delete': "Data opsisdis Jadwal Pemeliharaan Har berhasil dihapus",
        'not_found': "Data opsisdis Jadwal Pemeliharaan Har tidak ditemukan",
    },
    'trans_jadwal_har_dok': {
        'view': "Berhasil mendapatkan data opsisdis Jadwal Pemeliharaan Gardu Dokumen",
        'create': "Tambah data opsisdis Jadwal Pemeliharaan Gardu Dokumen berhasil",
        'update': "Ubah data opsisdis Jadwal Pemeliharaan Gardu Dokumen berhasil",
        'create_failed': "Tambah data opsisdis Jadwal Pemeliharaan Gardu Dokumen gagal",
        'update_failed': "Ubah data opsisdis Jadwal Pemeliharaan Gardu Dokumen gagal",
        'delete': "Data opsisdis Jadwal Pemeliharaan Gardu Dokumen berhasil dihapus",
        'not_found': "Data opsisdis Jadwal Pemeliharaan Gardu Dokumen tidak ditemukan",
    },
    'trans_jadwal_har_gardu': {
        'view': "Berhasil mendapatkan data opsisdis Jadwal Pemeliharaan Gardu ",
        'create': "Tambah data opsisdis Jadwal Pemeliharaan Gardu  berhasil",
        'update': "Ubah data opsisdis Jadwal Pemeliharaan Gardu  berhasil",
        'create_failed': "Tambah data opsisdis Jadwal Pemeliharaan Gardu  gagal",
        'update_failed': "Ubah data opsisdis Jadwal Pemeliharaan Gardu  gagal",
        'delete': "Data opsisdis Jadwal Pemeliharaan Gardu  berhasil dihapus",
        'not_found': "Data opsisdis Jadwal Pemeliharaan Gardu  tidak ditemukan",
    },
    'trans_tm_trafo_gi_jam': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Trafo GI Jam", 
        'not_found': "Data Opsis Laporan Beban Trafo GI Jam tidak ditemukan", 
    },
    'trans_tm_trafo_gi_hari': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Trafo GI Hari", 
        'not_found': "Data Opsis Laporan Beban Trafo GI Hari tidak ditemukan",  
    },
    'trans_tm_trafo_gi_bulan': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Trafo GI Bulan", 
        'not_found': "Data Opsis Laporan Beban Trafo GI Bulan tidak ditemukan", 
        
    },
    'trans_tm_trafo_gi_tahun': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Trafo GI Tahun", 
        'not_found': "Data Opsis Laporan Beban Trafo GI Tahun tidak ditemukan", 
        
    },
    'trans_tm_subsistem_jam': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Sub Sistem Jam", 
        'not_found': "Data Opsis Laporan Beban Sub Sistem Jam tidak ditemukan", 
    },
    'trans_tm_subsistem_hari': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Sub Sistem Hari", 
        'not_found': "Data Opsis Laporan Beban Sub Sistem Hari tidak ditemukan",  
    },
    'trans_tm_subsistem_bulan': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Sub Sistem Bulan", 
        'not_found': "Data Opsis Laporan Beban Sub Sistem Bulan tidak ditemukan", 
        
    },
    'trans_tm_subsistem_tahun': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Sub Sistem Tahun", 
        'not_found': "Data Opsis Laporan Beban Sub Sistem Tahun tidak ditemukan", 
        
    },
    'trans_tm_penyulang_jam': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Penyulang Jam", 
        'not_found': "Data Opsis Laporan Beban Penyulang Jam tidak ditemukan", 
        
    },
    'trans_tm_penyulang_hari': {
        'not_found': "Data Opsis Laporan Beban Penyulang Hari tidak ditemukan", 
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Penyulang Hari", 
    },
    'trans_tm_penyulang_bulan': {
        'not_found': "Data Opsis Laporan Beban Penyulang Bulan tidak ditemukan", 
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Penyulang Bulan", 
    },
    'trans_tm_penyulang_tahun': {
        'not_found': "Data Opsis Laporan Beban Penyulang Tahun tidak ditemukan", 
        'view': "Berhasil mendapatkan data Opsis Laporan Beban Penyulang Tahun", 
    },
    'trans_tm_up3_jam': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP3 Jam", 
        'not_found': "Data Opsis Laporan Beban UP3 Jam tidak ditemukan", 
    },
    'trans_tm_up3_hari': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP3 Hari",  
        'not_found': "Data Opsis Laporan Beban UP3 Hari tidak ditemukan", 
    },
    'trans_tm_up3_bulan': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP3 Bulan", 
        'not_found': "Data Opsis Laporan Beban UP3 Bulan tidak ditemukan", 
    },
    'trans_tm_up3_tahun': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP3 Tahun", 
        'not_found': "Data Opsis Laporan Beban UP3 Tahun tidak ditemukan", 
    },
    'trans_tm_up2b_jam': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP2B Jam", 
        'not_found': "Data Opsis Laporan Beban UP2B Jam tidak ditemukan", 
    },
    'trans_tm_up2b_hari': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP2B Hari", 
        'not_found': "Data Opsis Laporan Beban UP2B Hari tidak ditemukan", 
    },
    'trans_tm_up2b_bulan': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP2B Bulan", 
        'not_found': "Data Opsis Laporan Beban UP2B Bulan tidak ditemukan", 
    },
    'trans_tm_up2b_tahun': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UP2B Tahun", 
        'not_found': "Data Opsis Laporan Beban UP2B Tahun tidak ditemukan", 
    },
    'trans_tm_uid_jam': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UID Jam", 
        'not_found': "Data Opsis Laporan Beban UID Jam tidak ditemukan", 
    },
    'trans_tm_uid_hari': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UID Hari", 
        'not_found': "Data Opsis Laporan Beban UID Hari tidak ditemukan", 
    },
    'trans_tm_uid_bulan': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UID Bulan", 
        'not_found': "Data Opsis Laporan Beban UID Bulan tidak ditemukan", 
    },
    'trans_tm_uid_tahun': {
        'view': "Berhasil mendapatkan data Opsis Laporan Beban UID Tahun", 
        'not_found': "Data Opsis Laporan Beban UID Tahun tidak ditemukan", 
    },
    'penyulang_ufr': {
        'view': "Berhasil mendapatkan data Opsis UFR - Penyulang",
        'create': "Tambah data Opsis UFR - Penyulang berhasil",
        'update': "Ubah data Opsis UFR - Penyulang berhasil",
        'update_failed': "Ubah data Opsis UFR - Penyulang gagal",
        'delete': "Data Opsis UFR - Penyulang berhasil dihapus",
        'not_found': "Data Opsis UFR - Penyulang tidak ditemukan",
    },
    'frekuensi_5m': {
        'view': "Berhasil mendapatkan data opsisdis Frekuensi - 5M",
        'create': "Tambah data opsisdis Frekuensi - 5M berhasil",
        'update': "Ubah data opsisdis Frekuensi - 5M berhasil",
        'update_failed': "Ubah data opsisdis Frekuensi - 5M gagal",
        'delete': "Data opsisdis Frekuensi - 5M berhasil dihapus",
        'not_found': "Data opsisdis Frekuensi - 5M tidak ditemukan",
    },
    'frekuensi_his': {
        'view': "Berhasil mendapatkan data opsisdis Frekuensi - HIS",
        'create': "Tambah data opsisdis Frekuensi - HIS berhasil",
        'update': "Ubah data opsisdis Frekuensi - HIS berhasil",
        'update_failed': "Ubah data opsisdis Frekuensi - HIS gagal",
        'delete': "Data opsisdis Frekuensi - HIS berhasil dihapus",
        'not_found': "Data opsisdis Frekuensi - HIS tidak ditemukan",
    },
    'frekuensi_rtl': {
        'view': "Berhasil mendapatkan data opsisdis Frekuensi - RTL",
        'create': "Tambah data opsisdis Frekuensi - RTL berhasil",
        'update': "Ubah data opsisdis Frekuensi - RTL berhasil",
        'update_failed': "Ubah data opsisdis Frekuensi - RTL gagal",
        'delete': "Data opsisdis Frekuensi - RTL berhasil dihapus",
        'not_found': "Data opsisdis Frekuensi - RTL tidak ditemukan",
        'exists': "Data opsisdis Frekuensi - RTL Sudah ada silakan lakukan update",
    },
    'frekuensi_th': {
        'view': "Berhasil mendapatkan data opsisdis Frekuensi - TH",
        'create': "Tambah data opsisdis Frekuensi - TH berhasil",
        'update': "Ubah data opsisdis Frekuensi - TH berhasil",
        'update_failed': "Ubah data opsisdis Frekuensi - TH gagal",
        'delete': "Data opsisdis Frekuensi - TH berhasil dihapus",
        'not_found': "Data opsisdis Frekuensi - TH tidak ditemukan",
        'exists': "Data opsisdis Frekuensi - TH Sudah ada silakan lakukan update",
    },
    'sch_his_analog': {
        'view': "Berhasil mendapatkan data fasop spectrum histori analog",
        'create': "Tambah data fasop spectrum histori analog berhasil",
        'update': "Ubah data fasop spectrum histori analog berhasil",
        'update_failed': "Ubah data fasop spectrum histori analog gagal",
        'delete': "Data fasop spectrum histori analog berhasil dihapus",
        'not_found': "Data fasop spectrum histori analog tidak ditemukan",
    },
    'scd_his_rtu': {
        'view': "Berhasil mendapatkan data fasop spectrum histori rtu",
        'create': "Tambah data fasop spectrum histori rtu berhasil",
        'update': "Ubah data fasop spectrum histori rtu berhasil",
        'update_failed': "Ubah data fasop spectrum histori rtu gagal",
        'delete': "Data fasop spectrum histori rtu berhasil dihapus",
        'not_found': "Data fasop spectrum histori rtu tidak ditemukan",
    },
    'scd_his_digital': {
        'view': "Berhasil mendapatkan data fasop spectrum histori digital",
        'create': "Tambah data fasop spectrum histori digital berhasil",
        'update': "Ubah data fasop spectrum histori digital berhasil",
        'update_failed': "Ubah data fasop spectrum histori digital gagal",
        'delete': "Data fasop spectrum histori digital berhasil dihapus",
        'not_found': "Data fasop spectrum histori digital tidak ditemukan",
    },
    'scd_his_master': {
        'view': "Berhasil mendapatkan data fasop spectrum histori master",
        'create': "Tambah data fasop spectrum histori master berhasil",
        'update': "Ubah data fasop spectrum histori master berhasil",
        'update_failed': "Ubah data fasop spectrum histori master gagal",
        'delete': "Data fasop spectrum histori master berhasil dihapus",
        'not_found': "Data fasop spectrum histori master tidak ditemukan",
    },
    'scd_his_message': {
        'view': "Berhasil mendapatkan data fasop spectrum histori message",
        'create': "Tambah data fasop spectrum histori message berhasil",
        'update': "Ubah data fasop spectrum histori message berhasil",
        'update_failed': "Ubah data fasop spectrum histori message gagal",
        'delete': "Data fasop spectrum histori message berhasil dihapus",
        'not_found': "Data fasop spectrum histori message tidak ditemukan",
    },
    'scd_his_analog_30m': {
        'view': "Berhasil mendapatkan data fasop spectrum histori analog 30m",
        'create': "Tambah data fasop spectrum histori analog 30m berhasil",
        'update': "Ubah data fasop spectrum histori analog 30m berhasil",
        'update_failed': "Ubah data fasop spectrum histori analog 30m gagal",
        'delete': "Data fasop spectrum histori analog 30m berhasil dihapus",
        'not_found': "Data fasop spectrum histori analog 30m tidak ditemukan",
    },
    'scd_his_trip': {
        'view': "Berhasil mendapatkan data fasop spectrum histori trip",
        'create': "Tambah data fasop spectrum histori trip berhasil",
        'update': "Ubah data fasop spectrum histori trip berhasil",
        'update_failed': "Ubah data fasop spectrum histori trip gagal",
        'delete': "Data fasop spectrum histori trip berhasil dihapus",
        'not_found': "Data fasop spectrum histori trip tidak ditemukan",
    },
    'scd_his_rc': {
        'view': "Berhasil mendapatkan data fasop spectrum histori rc",
        'create': "Tambah data fasop spectrum histori rc berhasil",
        'update': "Ubah data fasop spectrum histori rc berhasil",
        'update_failed': "Ubah data fasop spectrum histori rc gagal",
        'delete': "Data fasop spectrum histori rc berhasil dihapus",
        'not_found': "Data fasop spectrum histori rc tidak ditemukan",
    },
    'scd_his_rc': {
        'view': "Berhasil mendapatkan data fasop spectrum histori rc",
        'create': "Tambah data fasop spectrum histori rc berhasil",
        'update': "Ubah data fasop spectrum histori rc berhasil",
        'update_failed': "Ubah data fasop spectrum histori rc gagal",
        'delete': "Data fasop spectrum histori rc berhasil dihapus",
        'not_found': "Data fasop spectrum histori rc tidak ditemukan",
    },
    'scd_kin_digital_harian': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja digital harian",
        'create': "Tambah data fasop spectrum kinerja digital harian berhasil",
        'update': "Ubah data fasop spectrum kinerja digital harian berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja digital harian gagal",
        'delete': "Data fasop spectrum kinerja digital harian berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja digital harian tidak ditemukan",
    },
    'scd_kin_digital_bulan': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja digital bulanan",
        'create': "Tambah data fasop spectrum kinerja digital bulanan berhasil",
        'update': "Ubah data fasop spectrum kinerja digital bulanan berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja digital bulanan gagal",
        'delete': "Data fasop spectrum kinerja digital bulanan berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja digital bulanan tidak ditemukan",
    },
    'scd_kin_rtu_harian': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja rtu harian",
        'create': "Tambah data fasop spectrum kinerja rtu harian berhasil",
        'update': "Ubah data fasop spectrum kinerja rtu harian berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja rtu harian gagal",
        'delete': "Data fasop spectrum kinerja rtu harian berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja rtu harian tidak ditemukan",
    },
    'scd_kin_rtu_bulan': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja rtu bulanan",
        'create': "Tambah data fasop spectrum kinerja rtu bulanan berhasil",
        'update': "Ubah data fasop spectrum kinerja rtu bulanan berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja rtu bulanan gagal",
        'delete': "Data fasop spectrum kinerja rtu bulanan berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja rtu bulanan tidak ditemukan",
    },
    'scd_kin_analog_harian': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja analog harian",
        'create': "Tambah data fasop spectrum kinerja analog harian berhasil",
        'update': "Ubah data fasop spectrum kinerja analog harian berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja analog harian gagal",
        'delete': "Data fasop spectrum kinerja analog harian berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja analog harian tidak ditemukan",
    },
    'scd_kin_analog_bulan': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja analog bulanan",
        'create': "Tambah data fasop spectrum kinerja analog bulanan berhasil",
        'update': "Ubah data fasop spectrum kinerja analog bulanan berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja analog bulanan gagal",
        'delete': "Data fasop spectrum kinerja analog bulanan berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja analog bulanan tidak ditemukan",
    },
    'scd_kin_master_harian': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja master harian",
        'create': "Tambah data fasop spectrum kinerja master harian berhasil",
        'update': "Ubah data fasop spectrum kinerja master harian berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja master harian gagal",
        'delete': "Data fasop spectrum kinerja master harian berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja master harian tidak ditemukan",
    },
    'scd_kin_master_bulan': {
        'view': "Berhasil mendapatkan data fasop spectrum kinerja master bulanan",
        'create': "Tambah data fasop spectrum kinerja master bulanan berhasil",
        'update': "Ubah data fasop spectrum kinerja master bulanan berhasil",
        'update_failed': "Ubah data fasop spectrum kinerja master bulanan gagal",
        'delete': "Data fasop spectrum kinerja master bulanan berhasil dihapus",
        'not_found': "Data fasop spectrum kinerja master bulanan tidak ditemukan",
    },
    'sch_analog_rtl': {
        'view': "Berhasil mendapatkan data fasop spectrum realtile analog",
        'create': "Tambah data fasop spectrum realtile analog berhasil",
        'update': "Ubah data fasop spectrum realtile analog berhasil",
        'update_failed': "Ubah data fasop spectrum realtile analog gagal",
        'delete': "Data fasop spectrum realtile analog berhasil dihapus",
        'not_found': "Data fasop spectrum realtile analog tidak ditemukan",
    }, 
    'sch_digital_rtl': {
        'view': "Berhasil mendapatkan data fasop spectrum realtile digital",
        'create': "Tambah data fasop spectrum realtile digital berhasil",
        'update': "Ubah data fasop spectrum realtile digital berhasil",
        'update_failed': "Ubah data fasop spectrum realtile digital gagal",
        'delete': "Data fasop spectrum realtile digital berhasil dihapus",
        'not_found': "Data fasop spectrum realtile digital tidak ditemukan",
    }, 
    'sch_master_rtl': {
        'view': "Berhasil mendapatkan data fasop spectrum realtile master",
        'create': "Tambah data fasop spectrum realtile master berhasil",
        'update': "Ubah data fasop spectrum realtile master berhasil",
        'update_failed': "Ubah data fasop spectrum realtile master gagal",
        'delete': "Data fasop spectrum realtile master berhasil dihapus",
        'not_found': "Data fasop spectrum realtile master tidak ditemukan",
    }, 
    'sch_rtu_rtl': {
        'view': "Berhasil mendapatkan data fasop spectrum realtile rtu",
        'create': "Tambah data fasop spectrum realtile rtu berhasil",
        'update': "Ubah data fasop spectrum realtile rtu berhasil",
        'update_failed': "Ubah data fasop spectrum realtile rtu gagal",
        'delete': "Data fasop spectrum realtile rtu berhasil dihapus",
        'not_found': "Data fasop spectrum realtile rtu tidak ditemukan",
    },
    'apkt_trans_jar': {
        'view': "Berhasil mendapatkan data apkt trans jar",
        'create': "Tambah data apkt trans jar berhasil",
        'update': "Ubah data apkt trans jar berhasil",
        'update_failed': "Ubah data apkt trans jar gagal",
        'delete': "Data apkt trans jar berhasil dihapus",
        'not_found': "Data apkt trans jar tidak ditemukan",
    },
    'apkt_trans_jar_det': {
        'view': "Berhasil mendapatkan data apkt trans jar det",
        'create': "Tambah data apkt trans jar det berhasil",
        'update': "Ubah data apkt trans jar det berhasil",
        'update_failed': "Ubah data apkt trans jar det gagal",
        'delete': "Data apkt trans jar det berhasil dihapus",
        'not_found': "Data apkt trans jar det tidak ditemukan",
    },
    'apkt_trans_log': {
        'view': "Berhasil mendapatkan data apkt trans log",
        'create': "Tambah data apkt trans log berhasil",
        'update': "Ubah data apkt trans log berhasil",
        'update_failed': "Ubah data apkt trans log gagal",
        'delete': "Data apkt trans log berhasil dihapus",
        'not_found': "Data apkt trans log tidak ditemukan",
    },
    'wp_bagian': {
        'view': "Berhasil mendapatkan data wp bagian",
        'create': "Tambah data wp bagian berhasil",
        'update': "Ubah data wp bagian berhasil",
        'update_failed': "Ubah data wp bagian gagal",
        'delete': "Data wp bagian berhasil dihapus",
        'not_found': "Data wp bagian tidak ditemukan",
    },
    'wp_hirarc': {
        'view': "Berhasil mendapatkan data wp hirac",
        'create': "Tambah data wp hirac berhasil",
        'update': "Ubah data wp hirac berhasil",
        'update_failed': "Ubah data wp hirac gagal",
        'delete': "Data wp hirac berhasil dihapus",
        'not_found': "Data wp hirac tidak ditemukan",
    },
    'wp_hirarc_detail': {
        'view': "Berhasil mendapatkan data wp hirac detail",
        'create': "Tambah data wp hirac detail berhasil",
        'update': "Ubah data wp hirac detail berhasil",
        'update_failed': "Ubah data wp hirac detail gagal",
        'delete': "Data wp hirac detail berhasil dihapus",
        'not_found': "Data wp hirac detail tidak ditemukan",
    },
    'wp_master_sop_jasa': {
        'view': "Berhasil mendapatkan data wp master sop jsa",
        'create': "Tambah data wp master sop jsa berhasil",
        'update': "Ubah data wp master sop jsa berhasil",
        'update_failed': "Ubah data wp master sop jsa gagal",
        'delete': "Data wp master sop jsa berhasil dihapus",
        'not_found': "Data wp master sop jsa tidak ditemukan",
    },
    'wp_qrc': {
        'view': "Berhasil mendapatkan data wp qrc",
        'create': "Tambah data wp qrc berhasil",
        'update': "Ubah data wp qrc berhasil",
        'update_failed': "Ubah data wp qrc gagal",
        'delete': "Data wp qrc berhasil dihapus",
        'not_found': "Data wp qrc tidak ditemukan",
    },
    'wp_qrc_detail': {
        'view': "Berhasil mendapatkan data wp qrc detail",
        'create': "Tambah data wp qrc detail berhasil",
        'update': "Ubah data wp qrc detail berhasil",
        'update_failed': "Ubah data wp qrc detail gagal",
        'delete': "Data wp qrc detail berhasil dihapus",
        'not_found': "Data wp qrc detail tidak ditemukan",
    },
    'wp_master_sop_jasa': {
        'view': "Berhasil mendapatkan data wp pertanyaan qrc",
        'create': "Tambah data wp pertanyaan qrc berhasil",
        'update': "Ubah data wp pertanyaan qrc berhasil",
        'update_failed': "Ubah data wp pertanyaan qrc gagal",
        'delete': "Data wp pertanyaan qrc berhasil dihapus",
        'not_found': "Data wp pertanyaan qrc tidak ditemukan",
    },
    'wp_qrc_tmp': {
        'view': "Berhasil mendapatkan data wp qrc tmp",
        'create': "Tambah data wp qrc tmp berhasil",
        'update': "Ubah data wp qrc tmp berhasil",
        'update_failed': "Ubah data wp qrc tmp gagal",
        'delete': "Data wp qrc tmp berhasil dihapus",
        'not_found': "Data wp qrc tmp tidak ditemukan",
    },
    'wp_online': {
        'view': "Berhasil mendapatkan data wp online",
        'create': "Tambah data wp online berhasil",
        'update': "Ubah data wp online berhasil",
        'update_failed': "Ubah data wp online gagal",
        'delete': "Data wp online berhasil dihapus",
        'not_found': "Data wp online tidak ditemukan",
    },
    'wp_online_pekerja': {
        'view': "Berhasil mendapatkan data wp aproval ttd",
        'create': "Tambah data wp online pekerja berhasil",
        'update': "Ubah data wp online pekerja berhasil",
        'update_failed': "Ubah data wp online pekerja gagal",
        'delete': "Data wp online pekerja berhasil dihapus",
        'not_found': "Data wp online pekerja tidak ditemukan",
    },
    'wp_aproval_ttd': {
        'view': "Berhasil mendapatkan data wp aproval ttd",
        'create': "Tambah data wp aproval ttd berhasil",
        'update': "Ubah data wp aproval ttd berhasil",
        'update_failed': "Ubah data wp aproval ttd gagal",
        'delete': "Data wp aproval ttd berhasil dihapus",
        'not_found': "Data wp aproval ttd tidak ditemukan",
    },
    'daf_sld_gi': {
        'view': "Berhasil mendapatkan data sld gi",
        'create': "Tambah data sld gi berhasil",
        'update': "Ubah data sld gi berhasil",
        'update_failed': "Ubah data sld gi gagal",
        'delete': "Data sld gi berhasil dihapus",
        'not_found': "Data sld gi tidak ditemukan",
    },
    'ref_pegawai': {
        'view': "Berhasil mendapatkan data master pegawai",
        'create': "Tambah data master pegawai berhasil",
        'update': "Ubah data master pegawai berhasil",
        'update_failed': "Ubah data master pegawai gagal",
        'delete': "Data master pegawai berhasil dihapus",
        'not_found': "Data master pegawai tidak ditemukan",
    },
    'wp_dok': {
        'view': "Berhasil mendapatkan data wp dok",
        'create': "Tambah data wp dok berhasil",
        'update': "Ubah data wp dok berhasil",
        'update_failed': "Ubah data wp dok gagal",
        'delete': "Data wp dok berhasil dihapus",
        'not_found': "Data wp dok tidak ditemukan",
    },
    'user_his_password': {
        'view': "Berhasil mendapatkan histori users password",
        'create': "Tambah histori users password berhasil",
        'update': "Ubah histori users password berhasil",
        'update_failed': "Ubah histori users password gagal",
        'delete': "histori users password berhasil dihapus",
        'not_found': "histori users password tidak ditemukan",
    },
    'scd_realtime': {
        'view': "Berhasil mendapatkan Realtime Scada", 
    },
    'ref_jenis_pembangkit': {
        'view': "Berhasil mendapatkan master ref jenis pembangkit",
        'create': "Tambah master ref jenis pembangkit berhasil",
        'update': "Ubah master ref jenis pembangkit berhasil",
        'update_failed': "Ubah master ref jenis pembangkit gagal",
        'delete': "master ref jenis pembangkit berhasil dihapus",
        'not_found': "master ref jenis pembangkit tidak ditemukan",
    },
    'ref_province': {
        'view': "Berhasil mendapatkan master ref province",
        'create': "Tambah master ref province berhasil",
        'update': "Ubah master ref province berhasil",
        'update_failed': "Ubah master ref province gagal",
        'delete': "master ref province berhasil dihapus",
        'not_found': "master ref province tidak ditemukan",
    },
    'ref_regency': {
        'view': "Berhasil mendapatkan master ref regency",
        'create': "Tambah master ref regency berhasil",
        'update': "Ubah master ref regency berhasil",
        'update_failed': "Ubah master ref regency gagal",
        'delete': "master ref regency berhasil dihapus",
        'not_found': "master ref regency tidak ditemukan",
    },
    'ref_district': {
        'view': "Berhasil mendapatkan master ref district",
        'create': "Tambah master ref district berhasil",
        'update': "Ubah master ref district berhasil",
        'update_failed': "Ubah master ref district gagal",
        'delete': "master ref district berhasil dihapus",
        'not_found': "master ref district tidak ditemukan",
    },
    'latihan': {
        'view': "Berhasil mendapatkan latihan",
        'create': "Tambah latihan berhasil",
        'update': "Ubah latihan berhasil",
        'update_failed': "Ubah latihan gagal",
        'delete': "latihan berhasil dihapus",
        'not_found': "latihan tidak ditemukan",
    },
    'scada_tree': {
        'realtime': "Berhasil mendapatkan data realtime",
        'create': "Tambah scada_tree berhasil",
        'update': "Ubah scada_tree berhasil",
        'update_failed': "Ubah scada_tree gagal",
        'delete': "scada_tree berhasil dihapus",
        'not_found': "scada_tree tidak ditemukan",
    },
    'ref_regu_petugas': { 
        'create': "Tambah Regu Petugas berhasil",
        'update': "Ubah Regu Petugas berhasil",
        'update_failed': "Ubah Regu Petugas gagal",
        'delete': "Regu Petugas berhasil dihapus",
        'not_found': "Regu Petugas tidak ditemukan",
    },
    'trans_pm': { 
        'create': "Tambah Trans PM berhasil",
        'update': "Ubah Trans PM berhasil",
        'update_failed': "Ubah Trans PM gagal",
        'delete': "Trans PM berhasil dihapus",
        'not_found': "Trans PM tidak ditemukan",
    },
    'trans_pm_detail': { 
        'create': "Tambah Trans PM Detail berhasil",
        'update': "Ubah Trans PM Detail berhasil",
        'update_failed': "Ubah Trans PM Detail gagal",
        'delete': "Trans PM Detail berhasil dihapus",
        'not_found': "Trans PM Detail tidak ditemukan",
    },
    'trans_aset_mutasi': { 
        'create': "Tambah Trans Aset Mutasi berhasil",
        'update': "Ubah Trans Aset Mutasi berhasil",
        'update_failed': "Ubah Trans Aset Mutasi gagal",
        'delete': "Trans Aset Mutasi berhasil dihapus",
        'not_found': "Trans Aset Mutasi tidak ditemukan",
    }, 
    'sch_his_message': { 
        'view': "Berhasil Mendapatkan Data Message(SOE)", 
    },
     'trans_tm_penyulang_jam': {
        'view': "Berhasil mendapatkan Data Penyulang Jam", 
        'not_found': "Data Penyulang tidak ada", 
    },
    'trans_tm_penyulang_hari': {
        'view': "Berhasil mendapatkan Data Penyulang Hari", 
        'not_found': "Data Penyulang tidak ada", 
    },
     'trans_tm_penyulang_bulan': {
        'view': "Berhasil mendapatkan Data Penyulang Bulan", 
        'not_found': "Data Penyulang tidak ada", 
    },
    'trans_tm_penyulang_tahun': {
        'view': "Berhasil mendapatkan Data Penyulang Tahun", 
        'not_found': "Data Penyulang tidak ada", 
    },
     'trans_tm_penyulang_jam': {
        'view': "Berhasil mendapatkan Data Penyulang Jam", 
        'not_found': "Data Penyulang tidak ada", 
    },
    'trans_tm_trafo_gi_hari': {
        'view': "Berhasil mendapatkan Data TrafoGI Hari", 
        'not_found': "Data TrafoGI tidak ada", 
    },
     'trans_tm_trafo_gi_bulan': {
        'view': "Berhasil mendapatkan Data TrafoGI Bulan", 
        'not_found': "Data TrafoGI tidak ada", 
    },
    'trans_tm_trafo_gi_tahun': {
        'view': "Berhasil mendapatkan Data TrafoGI Tahun", 
        'not_found': "Data TrafoGI tidak ada", 
    },
    'ref_ep_fiohl': { 
        'view': "Berhasil mendapatkan Data Ref Ep Fiohl",  
        'create': "Tambah Ref Ep Fiohl berhasil",
        'update': "Ubah Ref Ep Fiohl berhasil",
        'update_failed': "Ubah Ref Ep Fiohl gagal",
        'delete': "Ref Ep Fiohl berhasil dihapus",
        'not_found': "Ref Ep Fiohl tidak ditemukan",
    },
    'ref_ep_indikasi': { 
        'view': "Berhasil mendapatkan Data Ref Ep Indikasi",   
        'create': "Tambah Ref Ep Indikasi berhasil",
        'update': "Ubah Ref Ep Indikasi berhasil",
        'update_failed': "Ubah Ref Ep Indikasi gagal",
        'delete': "Ref Ep Indikasi berhasil dihapus",
        'not_found': "Ref Ep Indikasi tidak ditemukan",
    },
    'ref_ep_petugas': { 
        'view': "Berhasil mendapatkan Data Ref Ep Petugas",   
        'create': "Tambah Ref Ep Petugas berhasil",
        'update': "Ubah Ref Ep Petugas berhasil",
        'update_failed': "Ubah Ref Ep Petugas gagal",
        'delete': "Ref Ep Petugas berhasil dihapus",
        'not_found': "Ref Ep Petugas tidak ditemukan",
    },
    'ref_ep_rupiah': { 
        'view': "Berhasil mendapatkan Data Ref Ep Rupiah",   
        'create': "Tambah Ref Ep Rupiah berhasil",
        'update': "Ubah Ref Ep Rupiah berhasil",
        'update_failed': "Ubah Ref Ep Rupiah gagal",
        'delete': "Ref Ep Rupiah berhasil dihapus",
        'not_found': "Ref Ep Rupiah tidak ditemukan",
    },
    'ref_ep_cuaca': { 
        'view': "Berhasil mendapatkan Data Ref Ep Cuaca",  
        'create': "Tambah Ref Ep Cuaca berhasil",
        'update': "Ubah Ref Ep Cuaca berhasil",
        'update_failed': "Ubah Ref Ep Cuaca gagal",
        'delete': "Ref Ep Cuaca berhasil dihapus",
        'not_found': "Ref Ep Cuaca tidak ditemukan",
    },
    'ref_ep_penyebab_ggn': { 
        'view': "Berhasil mendapatkan Data Ref Ep Penyebab ggn",  
        'create': "Tambah Ref Ep Penyebab ggn berhasil",
        'update': "Ubah Ref Ep Penyebab ggn berhasil",
        'update_failed': "Ubah Ref Ep Penyebab ggn gagal",
        'delete': "Ref Ep Penyebab ggn berhasil dihapus",
        'not_found': "Ref Ep Penyebab ggn tidak ditemukan",
    },
    'ref_ep_fdir': { 
        'view': "Berhasil mendapatkan Data Ref Ep Fdir",  
        'create': "Tambah Ref Ep Fdir ggn berhasil",
        'update': "Ubah Ref Ep Fdir ggn berhasil",
        'update_failed': "Ubah Ref Ep Fdir ggn gagal",
        'delete': "Ref Ep Fdir ggn berhasil dihapus",
        'not_found': "Ref Ep Fdir ggn tidak ditemukan",
    },
    'trans_ep': { 
        'view': "Berhasil mendapatkan Data Trans Ep",  
        'view_peralatan': "Berhasil mendapatkan Data Trans Ep Peralatan",  
        'view_wa': "Berhasil mendapatkan Data Trans Ep Copy WA",  
        'create': "Tambah Trans Ep berhasil",
        'update': "Ubah Trans Ep berhasil",
        'update_failed': "Ubah Trans Ep gagal",
        'delete': "Trans Ep berhasil dihapus",
        'not_found': "Trans Ep tidak ditemukan",
    },
    'trans_ep_laporan': { 
        'view': "Berhasil mendapatkan Data Trans Ep Laporan",  
        'create': "Tambah Trans Ep Laporan berhasil",
        'update': "Ubah Trans Ep Laporan berhasil",
        'update_failed': "Ubah Trans Ep Laporan gagal",
        'delete': "Trans Ep Laporan berhasil dihapus",
        'not_found': "Trans Ep Laporan tidak ditemukan",
    },
    'trans_ep_peralatan': { 
        'view': "Berhasil mendapatkan Data Trans Ep Peralatan",  
        'create': "Tambah Trans Ep Peralatan berhasil",
        'update': "Ubah Trans Ep Peralatan berhasil",
        'update_failed': "Ubah Trans Ep Peralatan gagal",
        'delete': "Trans Ep Peralatan berhasil dihapus",
        'not_found': "Trans Ep Peralatan tidak ditemukan",
    },
    'trans_ep_section': { 
        'view': "Berhasil mendapatkan Data Trans Ep Section",  
        'cant_add': "Tidak Bisa Menambahkan Nyala Bertahap karena sudah normal",  
        'create': "Tambah Trans Ep Section berhasil",
        'update': "Ubah Trans Ep Section berhasil",
        'update_failed': "Ubah Trans Ep Section gagal",
        'delete': "Trans Ep Section berhasil dihapus",
        'not_found': "Trans Ep Section tidak ditemukan", 
    },

    'realtime_scada':{
        'view': "Berhasi mendapakan data Realtime Scada",
    },
    'soe_alarm_proteksi':{
        'view': "Berhasi mendapakan data SOE Alarm Proteksi",
    },
    'histori_rc':{
        'view': "Berhasi mendapakan data Histori RC",
    },
    'kinerja_rc':{
        'view': "Berhasi mendapakan data Kinerja RC",
    },
    'histori_peralatan_scd':{
        'view': "Berhasi mendapakan data Histori Peralatan SCADA",
    },
    'kinerja_peralatan_scd':{
        'view': "Berhasi mendapakan data Kinerja Peralatan SCADA",
    },
}

def message(msg):
    try:
        keys = msg.split(".")
        newarray = array.get(keys[0], {}).get(keys[1])
        return newarray
    except ValueError:
        return 'not found'
