from django.db import models

# Create your models here.
EXPORT_HEADERS = [ 'ID_TRAFO_GI', 'NAMA_TRAFO_GI', 'ALAMAT','ID_PARENT_LOKASI', 'KAPASITAS',
                    'SUB_SISTEM', 'PEMILIK', 'STATUS_TRAFO','JENIS_TRAFO','I_MAX','RATIO_CT',
                    'RATIO_VT','FX_METER_PEMBANDING','DEF_PENGUKURAN_TEG_PRIMER','DEF_PENGUKURAN_TEG_SEKUNDER','DEF_NILAI_COSQ',
                    'JENIS_LAYANAN','LATITUDE','LONGITUDE','COVERAGE','KVA','PHASE','STATUS','SINKRON_DATA','ID_I',
                    'ID_V','ID_P','ID_AMR','ID_PORTAL_EXT','URL_WEBSERVICE','EVENT_UPLOAD']
EXPORT_HEADERS_DATA = [ 'ID_TRAFO_GI', 'NAMA_TRAFO_GI', 'ALAMAT','ID_PARENT_LOKASI','NAMA_PARENT_LOKASI', 'KAPASITAS',
                    'SUB_SISTEM', 'PEMILIK', 'STATUS_TRAFO','JENIS_TRAFO','I_MAX','RATIO_CT',
                    'RATIO_VT','FX_METER_PEMBANDING','DEF_PENGUKURAN_TEG_PRIMER','DEF_PENGUKURAN_TEG_SEKUNDER','DEF_NILAI_COSQ',
                    'JENIS_LAYANAN','LATITUDE','LONGITUDE','COVERAGE','KVA','PHASE','STATUS','SINKRON_DATA','ID_I',
                    'ID_V','ID_P','ID_AMR','ID_PORTAL_EXT','URL_WEBSERVICE']