# Generated by Django 3.2 on 2022-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefAset',
            fields=[
                ('id_ref_aset', models.AutoField(db_column='id_ref_aset', primary_key=True, serialize=False)),
                ('jenis_aset', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500)),
                ('lat', models.FloatField(blank=True, db_column='lat', default=None, null=True)),
                ('lon', models.FloatField(blank=True, db_column='lon', default=None, null=True)),
                ('id_trans_pm', models.IntegerField(blank=True, default=None, null=True)),
                ('id_aset_mutasi', models.IntegerField(blank=True, default=None, null=True)),
                ('tgl_buat', models.DateField(auto_now_add=True, null=True)),
                ('tgl_update', models.DateField(auto_now=True, null=True)),
                ('no_aset_interanl', models.IntegerField(blank=True, default=None, null=True)),
                ('no_aset_exteranl', models.IntegerField(blank=True, default=None, null=True)),
                ('nama', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500)),
                ('no_seri', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500)),
                ('tipe', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500)),
                ('tahun', models.IntegerField(blank=True, default=None, null=True)),
                ('dimensi_lebar', models.IntegerField(blank=True, default=None, null=True)),
                ('dimensi_panjang', models.IntegerField(blank=True, default=None, null=True)),
                ('dimensi_tinggi', models.IntegerField(blank=True, default=None, null=True)),
                ('dimensi_satuan', models.IntegerField(blank=True, default=None, null=True)),
                ('massa_berat', models.IntegerField(blank=True, default=None, null=True)),
                ('massa_satuan', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'ref_aset',
                'managed': False,
            },
        ),
    ]
