# Generated by Django 3.2 on 2022-04-21 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jabatan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalManagementWP',
            fields=[
                ('id_approval_management_wp', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('nama_jabatan', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('nama_bagian', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('id_jabatan', models.ForeignKey(blank=True, db_column='id_jabatan', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jabatan.jabatan')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ref_wm_approval_management_wp',
                'managed': True,
            },
        ),
    ]
