from django.db import models

EXPORT_HEADERS = ['ID_GARDU_HUBUNG', 'NAMA_GARDU_HUBUNG','ALAMAT', 'LATITUDE','LONGITUDE','STATUS','EVENT_UPLOAD']

EXPORT_HEADERS_DATA = ['ID_GARDU_HUBUNG', 'NAMA_GARDU_HUBUNG','ALAMAT', 'LATITUDE','LONGITUDE','STATUS']