from django.db import models

EXPORT_HEADERS = [ 'ID_SECTION','NAMA_SECTION', 'ALAMAT','ID_GARDU_INDUK','ID_TRAFO_GI','ID_PENYULANG','ID_ZONE','LATITUDE','LONGITUDE','STATUS','EVENT_UPLOAD']

EXPORT_HEADERS_DATA = ['ID_SECTION','NAMA_SECTION', 'ALAMAT','NAMA_GARDU_INDUK','NAMA_TRAFO_GI','NAMA_PENYULANG','ID_ZONE','NAMA_ZONE','LATITUDE','LONGITUDE','STATUS']