# Generated by Django 3.2 on 2022-04-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref_lokasi', '__first__'),
        ('point_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FASOPMASTER',
            fields=[
                ('point_number', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=18)),
                ('b3text', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=18)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('faktor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=18)),
                ('jenis', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=18)),
                ('send_telegram', models.IntegerField(blank=True, null=True)),
                ('kinerja', models.IntegerField(blank=True, null=True)),
                ('id_pointtype', models.ForeignKey(blank=True, db_column='id_pointtype', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_type.pointtype')),
                ('id_ref_lokasi', models.ForeignKey(blank=True, db_column='id_ref_lokasi', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ref_lokasi.reflokasi')),
            ],
            options={
                'db_table': 'scd_ref_master',
                'managed': True,
            },
        ),
    ]
