# Generated by Django 3.2 on 2022-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('privileges', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
