from django.db import models

EXPORT_HEADERS = [ 'ID_TRAFO_GD','NAMA_TRAFO_GD', 'ALAMAT','ID_GARDU_INDUK','ID_TRAFO_GI','ID_PENYULANG','ID_ZONE','ID_SECTION','ID_SEGMENT','ID_GARDU_DISTRIBUSI','LATITUDE','LONGITUDE','STATUS','EVENT_UPLOAD']

EXPORT_HEADERS_DATA = ['ID_TRAFO_GD','NAMA_TRAFO_GD', 'ALAMAT','NAMA_GARDU_INDUK','NAMA_TRAFO_GI','NAMA_PENYULANG','NAMA_ZONE','NAMA_SECTION','ID_SEGMENT','ID_GARDU_DISTRIBUSI','NAMA_GARDU_DISTRIBUSI','LATITUDE','LONGITUDE','STATUS']
