from django.db import models

# Create your models here.


EXPORT_HEADERS = [ 'ID_ZONE','NAMA_ZONE', 'ALAMAT','ID_GARDU_INDUK','ID_TRAFO_GI','ID_PENYULANG','LATITUDE','LONGITUDE','STATUS','EVENT_UPLOAD']

EXPORT_HEADERS_DATA = ['ID_ZONE','NAMA_ZONE', 'ALAMAT','NAMA_GARDU_INDUK','NAMA_TRAFO_GI','ID_PENYULANG','NAMA_PENYULANG','LATITUDE','LONGITUDE','STATUS']